export default {
  login: {
    login: "Sing In",
    email: "Email",
    phone: "Phone",
    phone_number: "Phone number",
    password: "Password",
    forget_pw: "Forgot Password?",
    country_number: "Country number",
    pw_placeholder1: "Please input your email",
    pw_placeholder2: "Please input your phone number",
    pw_placeholder3: "Please input your password",
    pw_placeholder4: "Please input the country number",
    no_account_con1: "Has not an account?",
    no_account_con2: "Go to sign up",
    no_account_warning: "Can not find this account",
    login_success: "Signed in successfully",
    login_failed: "Failed to sign in",
    network_error: "Network Error",
  },
  register: {
    security: "Security Verification",
    security_con: "Drag the slider to make the image angle positive",
    security_result_success: "Verification success",
    security_result_failed: "Verification failed",
    security_result_pedding: "Waiting for sliding verification",
    create_user_account: "Create Your account",
    create_user_account: "Create your account",
    create_guest_account: "Create a guest account",
    has_account: "Has an account？",
    go_login: "Go to login",
    email: "Email",
    phone: "Phone",
    phone_number: "Phone number",
    login_password: "Login password",
    trade_password: "Trade password",
    forget_pw: "Forget password?",
    country_number: "Country number",
    pw_placeholder1: "Please input your email",
    pw_placeholder2: "Please input your phone number",
    pw_placeholder3: "At least 8 letters for password",
    pw_placeholder4: "Please input the country number",
    pw_placeholder5: "Please input the trade password",
    pw_placeholder6: "Please input the invite code",
    invite_code: "Invite code",
    agree_con1: "I agree with",
    agree_con2: "security policy",
    agree_con3: "and",
    agree_con4: "user rules",
    register_success: "Signed up successfully",
    register_failed: "Failed to sign up",
    network_error: "Network Error",
    next: "Go on",
    code_email: "Email ",
    code_phone: "Phone ",
    code_verify: "Verification",
    code_con1: "Already sent verification code to your ",
    code_con2: "Input 6 letter code",
    code_jump: "Skip verify",
    code_again: 'Send again',
    code_jump_title: "Skip verification and go on to register",
    code_jump_confirm: "Confirm",
    success_sign_up: "Succes sign up",
    success_btn: "Identity & Google Authenticator",
    success_finish: "Finish",
  },
  password_level: {
    weak: "Weak",
    normal: "Normal",
    strong: "Strong"
  },
  code_input: {
    btn_text1: "Next",
    btn_text2: "Bound",
  },
  user_page: {
    login_out: "Sign In / Sign Out",
    recommended_user: "Recommended User",
    social_user: "Social User",
    recommend_bonus: "Recommend Bonus",
    ad_head: "Get invested crypto",
    ad_con1: "Virtual coin",
    ad_con2: "Proceeds on sale",
    receive_payment: "Receiving Account",
    verify_identity: "Identity verify",
    google_verification: "Google Authenticator",
    already_verified: "Set",
    pendding_verified: "Pendding",
    not_verified: "Unset",
    already_set: "Bounded",
    not_set: "Unbounded",
    recommend_friend: "Recommend to friends",
    set_language: "Language",
    security: "Security",
    about: "About",
    logout: "Log out",
    already_set_google: "Bounded GGA",
    not_set_google_yet: "Unbounded GGA",
    message_box_con: "Really want to log out?",
    message_box_confirm: "Cancel",
    message_box_cancel: "Confirm",
  },
  kyc: {
    page_title: "Identity Authentication",
    first_basic_info: "Basic Information",
    first_upload_card: "Upload certificate",
    first_title: "Verify your identity",
    first_description: "Due to financial regulations we need to ensure your details exactly match your government issued ID",
    first_legal_name: "Legal name",
    first_card_id: "ID number",
    first_birthday: "Date of Birth",
    first_birthday_placeholder: "Please select your date of birth",
    first_btn: "Next step",
    first_confirm: "Confirm",
    second_basic_info: "Basic Information",
    second_upload_card: "Upload certificate",
    second_title: "Upload certificate",
    second_description: "Please upload your ID for identity verification only",
    second_card_front: "Front of the document",
    second_card_back: "Back of the document",
    second_card_hand: "Holding certificate",
    second_upload_rule: "Upload Requirements",
    second_upload_description: "When taking photos, make sure the ID card frame is complete, the writing is clear, and the brightness is uniform.",
    second_standard_img: "Standard shooting",
    second_failed1: "Incomplete shooting",
    second_failed2: "Blurred shooting",
    second_failed3: "Excessive flash",
    second_btn: "Finish",
    final_title: "Identity authentication submitted successfully",
    final_description: "Please wait for the review results. We will strictly keep your identity information confidential.",
    final_ok: "OK",
    status_success: "Authentication successful",
    status_pendding: "Under review",
    status_pendding_description: "Identity authentication has been submitted for review, please wait patiently",
    status_failure: "Authentication failed",
    status_card_no: "ID number",
    status_birthday: "Date of Birth",
    status_reverify: "Recertification",
    status_service: "Contact Customer Service",
  },
  google_auth: {
    page_title: "Google Authenticator",
    from_register_skip: "Skip",
    google_title: "Bound Google Auth",
    bound_success: "Successful bound",
    copy_success: "Copied",
    confirm_title: "Skip bounding google auth?",
    google_result_title: "Bound",
    google_result_con: "If you have any questions, please contact online customer service",
    google_result_btn: "OK"
  },
  service: {
    page_title: "Online Customer Service",
    first_message: "Hello, how can I help you?",
    input_message: "Please input message..."
  },
  language: {
    page_title: "Language"
  },
  safety: {
    page_title: "Safety",
    change_login_pw: "Login password",
    change_trade_pw: "Trade password",
    bind_google_auth: "Google authenticator",
    google_status_not: "No bind",
    google_status_ok: "Bound",
    no_google_dialog_title: "Google Authenticator",
    no_google_dialog_con: "You have not bound Google Authenticator, go for it?",
  },
  change_login_pw: {
    page_title: "Change login password",
    origin_pw: "Origin password",
    origin_pw_placeholder: "Please input origin password",
    new_pw: "New password",
    new_pw_placeholder: "Input at least 8 letters",
    confirm_pw: "Confirm new password",
    confirm_pw_placeholder: "Please input new password again",
    btn: "Change",
    no_match_noti: "New passwords are not matched"
  },
  change_trade_pw: {
    page_title: "Change trade password",
    origin_pw: "Origin password",
    origin_pw_placeholder: "Please input origin password",
    new_pw: "New password",
    new_pw_placeholder: "Input at least 8 letters",
    confirm_pw: "Confirm new password",
    confirm_pw_placeholder: "Please input new password again",
    btn: "Change",
    no_match_noti: "New passwords are not matched"
  },
  form: {
    all: "All",
  },
  assets: {
    recharge: "Recharge",
    withdraw: "Withdraw",
    transfer: "Transfer",
    financialRecords: "Details",
  },
  topUpCrypto: {
    recharge: "Recharge",
    rechargeRecord: "Recharge record",
    cryptocurrency: "Crypto currency",
    bankCard: "Bank card",
    currency: "Currency",
    network: "Network",
    rechargeAmount: "Recharge amount",
    inputPlaceholder: "Please enter",
    confirm: "Confirm",
    currencySelection: "Currency selection",
    searchPlaceholder: "Enter currency",
    networkSelection: "Network selection",
  },
  withdraw: {
    withdraw: "Withdraw",
    withdrawRecord: "Withdraw record",
    cryptocurrency: "Crypto currency",
    bankCard: "Bank card",
    currency: "Currency",
    network: "Network",
    confirm: "Confirm",
    currencySelection: "Currency selection",
    searchPlaceholder: "Enter currency",
    addPaymentMethod: "Add payment method",
    withdrawable: "Withdrawable",
    withdrawalAmount: "Withdrawal amount",
    serviceFee: "Service fee",
    receiptAccount: "Receipt account",
    change: "Change",
    accountSelection: "Account selection",
  },
  recharging: {
    recharge: "Recharge",
    countdown: "Countdown",
    QRcodeExpired: "QR code expired",
    walletAddress: "Payee's wallet address",
    copy: "Copy",
    tip1: "Tip: Please complete the recharge within the deadline",
    tip2: "Order expiration and cancellation",
    success: "Success",
    fail: "Fail",
    finish: "Finish",
  },
  withdrawInfo: {
    title: "Withdrawal details",
    successful: "Successful",
    failed: "Failed",
    failurePrompt: "Please withdraw again or contact customer service",
    processing: "Processing",
    processingTip: "Please wait for the withdrawal result",
    withdrawalAmount: "Amount",
    receivingAccount: "Account",
    withdrawalCurrency: "Currency",
    withdrawalNetwork: "Network",
    orderNumber: "Order Number",
    withdrawalTime: "Time",
  },
  transfer: {
    transferRecord: "transfer record",
  },
  recordList: {
    financialRecords: "Financial records",
    rechargeRecord: "Recharge",
    withdrawalRecord: "Withdrawal",
    transfer: "Transfer",
  },
  accountMap: {
    cashAccount: "Cash account",
    stockAccount: "Stock account",
    contractAccount: "Contract account",
    foreignExchangeAccount: "Foreign exchange account",
  },
  topUpStatusMap: {
    review: "Under review",
    success: "Successful",
    fail: "Failed",
    unknown: "Unknown",
  },
  withdrawStatusMap: {
    review: "Under review",
    success: "Successful",
    fail: "Failed",
    unknown: "Unknown",
  },
  common:{
      stock:"Stock",
      crypto:"合约",
      AI:"交易机器人",
      IPO:"IPO",
      closed:"Closed"
  },
  home:{
      login:'Login',
      loginDesc:"Login is required to view assets",
      totalAssets:"Total assets",
      fastTrading:"Fast trading",
      recharge:"Techarge",
      today:"Today",
      index:"Index",
      hotSale:"Hot sale",
      marketRecommend:"Market",
      selfSelectedRecommend:"Self selected"
  },
  market:{
      stock:{
          updateTime:"更新时间",
          riseAndFall:"涨跌分布",
          up:'上涨',
          down:'下跌',
          limitUpPursuit:"涨停追击",
          profitMakingEffect:"赚钱效应",
          strong:"强",
          weak:'弱',
          contrast:"涨跌停对比",
          performance:"做涨停今表现",
          hot:"热门股",
          upList:"涨幅榜",
          downList:"跌幅榜"
      }
  },
};

