export default {
  common: {
    stock: "Aktien",
    crypto: "Krypto",
    AI: "Handelsroboter",
    IPO: "Börsengang",
    closed: "Markt geschlossen",
    no_data: "Keine Daten verfügbar",
    day: "Tag",
    hour: "Stunde",
    min: "Minute",
    no_more: "Keine weiteren Daten",
    no_wallet: "Kein Zahlungskonto verfügbar",
  },
  login: {
    login: "Anmelden",
    email: "E-Mail",
    phone: "Telefon",
    phone_number: "Telefonnummer",
    password: "Passwort",
    forget_pw: "Passwort vergessen?",
    country_number: "Ländervorwahl",
    pw_placeholder1: "Ihre E-Mail-Adresse",
    pw_placeholder2: "Ihre Telefonnummer",
    pw_placeholder3: "Bitte geben Sie Ihr Passwort ein",
    pw_placeholder4: "Vorwahl eingeben",
    no_account_con1: "Kein Konto?",
    no_account_con2: "Registrieren",
    no_account_warning: "Konto existiert nicht",
    login_success: "Anmeldung erfolgreich",
    login_failed: "Anmeldung fehlgeschlagen",
    network_error: "Netzwerkfehler",
  },
  forget_pw: {
    title: "Passwort vergessen",
    email_phone: "E-Mail/Telefonnummer",
    success: "Passwort wurde zurückgesetzt",
    back: "Zurück zur Anmeldung",
    get_back: "Passwort wiederherstellen",
  },
  register: {
    security: "Sicherheitsüberprüfung",
    security_con:
      "Schieben Sie den Schieberegler, um den Bildwinkel gerade zu machen",
    security_result_success: "Überprüfung erfolgreich",
    security_result_failed: "Überprüfung fehlgeschlagen",
    security_result_pending: "Warten auf Schieberegler-Überprüfung",
    create_user_account: "Erstellen Sie Ihr Konto",
    create_guest_account: "Gastkonto erstellen",
    has_account: "Haben Sie ein Konto?",
    go_login: "Zur Anmeldung",
    email: "E-Mail",
    phone: "Telefon",
    phone_number: "Telefonnummer",
    login_password: "Anmeldepasswort",
    trade_password: "Handels-Passwort",
    forget_pw: "Passwort vergessen?",
    country_number: "Ländervorwahl wählen",
    pw_placeholder1: "Ihre E-Mail-Adresse",
    pw_placeholder2: "Ihre Telefonnummer",
    pw_placeholder3: "Mindestens 8 Zeichen für das Passwort",
    pw_placeholder4: "Vorwahl eingeben",
    pw_placeholder5: "Bitte geben Sie Ihr Handels-Passwort ein",
    pw_placeholder6: "Bitte geben Sie Ihren Einladungs-Code ein",
    invite_code: "Einladungs-Code",
    agree_con1: "Ich stimme zu",
    agree_con2: "Datenschutzerklärung",
    agree_con3: "und",
    agree_con4: "Nutzungsbedingungen",
    register_success: "Registrierung erfolgreich",
    register_failed: "Registrierung fehlgeschlagen",
    network_error: "Netzwerkfehler",
    next: "Weiter",
    code_email: "E-Mail",
    code_phone: "Telefon",
    code_verify: "Verifizieren",
    code_con1: "Wir haben den Verifizierungscode an Ihre",
    code_con2: "gesendet. Bitte geben Sie den 6-stelligen Code ein",
    code_jump: "Verifizierung überspringen",
    code_again: "Erneut senden",
    code_jump_title:
      "Das Überspringen der Verifizierung führt die Registrierung fort. Möchten Sie fortfahren?",
    code_jump_confirm: "Bestätigen",
    success_sign_up: "Registrierung erfolgreich",
    success_btn: "Zwei-Faktor-Authentifizierung & Identitätsprüfung",
    success_finish: "Fertigstellen",
    no_email_error: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    no_phone_error: "Bitte geben Sie eine Telefonnummer ein",
    no_login_pw_error: "Bitte geben Sie ein Passwort ein",
    login_pw_length_error: "Passwort muss mindestens 8 Zeichen lang sein",
    no_trade_pw_error: "Bitte geben Sie das Handels-Passwort ein",
    no_agree_error:
      "Bitte stimmen Sie zuerst der Datenschutzerklärung und den Nutzungsbedingungen zu",
    // network_error: "Netzwerkfehler. Bitte versuchen Sie es erneut",
    guest_account: "Gastkonto",
    already_get_virtual: "Virtuelles Guthaben wurde gutgeschrieben",
    user_already_exist: "Dieser Benutzer ist bereits registriert",
    enter_graphic_number: "Bitte geben Sie den Bild-Code ein",
    not_clear: "Unklar? Bild wechseln",
    enter_verify_code: "Geben Sie den Verifizierungscode ein",
    verify_code_error:
      "Fehler beim Abrufen des Codes. Bitte aktualisieren Sie manuell",
  },
  password_level: {
    weak: "Schwach",
    normal: "Mittel",
    strong: "Stark",
  },
  code_input: {
    btn_text1: "Weiter",
    btn_text2: "Binden",
  },
  user_page: {
    login_out: "Registrieren/Anmelden",
    recommended_user: "Empfohlene Nutzer",
    social_user: "Netzwerk-Nutzer",
    recommend_bonus: "Empfehlungsbonus",
    ad_head: "Simuliertes Investitionsguthaben erhalten",
    ad_head1: "Registrierung Belohnung erhalten",
    ad_con3: "1000 USDT",
    ad_con1: "Simuliertes Investieren",
    ad_con2: "Erträge im Verkauf",
    receive_payment: "Zahlungskonto",
    verify_identity: "Identitätsverifizierung",
    google_verification: "Google Authenticator",
    already_verified: "Verifiziert",
    pending_verified: "Wird überprüft",
    not_verified: "Nicht verifiziert",
    already_set: "Gebunden",
    not_set: "Nicht gebunden",
    recommend_friend: "Freunde empfehlen",
    set_language: "Sprache",
    security: "Sicherheit",
    about: "Über",
    logout: "Abmelden",
    already_set_google: "Google Authenticator ist gebunden",
    not_set_google_yet: "Google Authenticator ist nicht gebunden",
    message_box_con: "Sind Sie sicher, dass Sie sich abmelden möchten?",
    message_box_confirm: "Bestätigen",
    message_box_cancel: "Abbrechen",
    get_demo_coin: "Jetzt abholen",
  },
  kyc: {
    page_title: "Identitätsverifizierung",
    first_basic_info: "Grundlegende Informationen",
    first_upload_card: "Dokumenten-Upload",
    first_title: "Verifizieren Sie Ihre Identität",
    first_description:
      "Gemäß den Finanzvorschriften müssen wir sicherstellen, dass Ihre Angaben mit den auf Ihrem von der Regierung ausgestellten Ausweis übereinstimmen.",
    first_legal_name: "Rechtlicher Name",
    first_card_id: "Ausweisnummer",
    first_birthday: "Geburtsdatum",
    first_birthday_placeholder: "Bitte wählen Sie ein Geburtsdatum",
    first_btn: "Weiter",
    first_confirm: "Bestätigen",
    second_basic_info: "Grundlegende Informationen",
    second_upload_card: "Dokumenten-Upload",
    second_title: "Dokumenten-Upload",
    second_description:
      "Bitte laden Sie Ihr Dokument hoch, nur zur Identitätsverifikation.",
    second_card_front: "Vorderseite des Ausweises",
    second_card_back: "Rückseite des Ausweises",
    second_card_hand: "Handgehaltenes Ausweisdokument",
    second_upload_rule: "Upload-Vorgaben",
    second_upload_description:
      "Stellen Sie sicher, dass der Rand des Ausweises sichtbar, die Schrift klar und die Beleuchtung gleichmäßig ist.",
    second_standard_img: "Standardaufnahme",
    second_failed1: "Unvollständige Aufnahme",
    second_failed2: "Unklare Aufnahme",
    second_failed3: "Überbelichtung",
    second_btn: "Fertigstellen",
    final_title: "Identitätsverifizierung erfolgreich eingereicht",
    final_description:
      "Bitte warten Sie auf das Prüfungsergebnis. Wir werden Ihre Identitätsinformationen vertraulich behandeln.",
    final_ok: "Okay",
    status_success: "Verifizierung erfolgreich",
    status_pending: "In Prüfung",
    status_pending_description:
      "Die Identitätsverifizierung wurde zur Prüfung eingereicht. Bitte warten Sie geduldig.",
    status_failure: "Verifizierung fehlgeschlagen",
    status_card_no: "Ausweisnummer",
    status_birthday: "Geburtsdatum",
    status_reverify: "Erneut verifizieren",
    status_service: "Kundendienst kontaktieren",
    verify_success: "Prüfung bestanden",
    verify_failure: "Prüfung nicht bestanden",
    id_photo_requirement: "Fotoupload-Anforderungen",
  },
  google_auth: {
    page_title: "Google Authenticator",
    from_register_skip: "Überspringen",
    google_title: "Google Authenticator binden",
    bound_success: "Erfolgreich gebunden",
    copy_success: "Erfolgreich kopiert",
    confirm_title:
      "Möchten Sie das Binden des Google Authenticators wirklich überspringen?",
    google_result_title: "Gebunden",
    google_result_con:
      "Bei Problemen können Sie den Online-Kundendienst kontaktieren",
    google_result_btn: "Okay",
    google_input_title: "Google Verifizierungscode",
    google_input_con: "Bitte geben Sie den 6-stelligen Code ein",
    google_input_btn_cancel: "Abbrechen",
    google_input_btn_confirm: "Bestätigen",
  },
  service: {
    page_title: "Kundendienst",
    message_title: "Unser Kundendienst hilft Ihnen gerne",
    first_message: "Hallo, wie kann ich Ihnen helfen?",
    input_message: "Bitte geben Sie eine Nachricht ein...",
  },
  language: {
    page_title: "Sprachauswahl",
  },
  safety: {
    page_title: "Sicherheit",
    change_login_pw: "Anmeldepasswort",
    change_trade_pw: "Handels-Passwort",
    bind_google_auth: "Google Authenticator",
    google_status_not: "Nicht gebunden",
    google_status_ok: "Gebunden",
    no_google_dialog_title: "Google Authenticator",
    no_google_dialog_con:
      "Sie haben den Google Authenticator noch nicht gebunden. Möchten Sie ihn jetzt binden?",
    success_title: "Aktion erfolgreich",
    success_btn: "Schließen",
  },
  change_login_pw: {
    page_title: "Anmeldepasswort ändern",
    origin_pw: "Altes Passwort",
    origin_pw_placeholder: "Geben Sie Ihr altes Passwort ein",
    new_pw: "Neues Passwort",
    new_pw_placeholder: "Mindestens 8 Zeichen für das Passwort",
    confirm_pw: "Neues Passwort bestätigen",
    confirm_pw_placeholder: "Bitte geben Sie das neue Passwort erneut ein",
    btn: "Ändern",
    no_match_noti: "Die beiden Passwörter stimmen nicht überein",
  },
  change_trade_pw: {
    page_title: "Handels-Passwort ändern",
    origin_pw: "Altes Passwort",
    origin_pw_placeholder: "Geben Sie Ihr altes Passwort ein",
    new_pw: "Neues Passwort",
    new_pw_placeholder: "Mindestens 8 Zeichen für das Passwort",
    confirm_pw: "Neues Passwort bestätigen",
    confirm_pw_placeholder: "Bitte geben Sie das neue Passwort erneut ein",
    btn: "Ändern",
    no_match_noti: "Die beiden Passwörter stimmen nicht überein",
  },
  account: {
    page_title: "Zahlungskonto",
    crypto: "Kryptowährung",
    no_data: "Kein Zahlungskonto vorhanden",
    bank: "Bankkarte",
    no_kyc_title: "Identität nicht verifiziert",
    no_kyc_con1: "Ihre Identität wurde noch nicht verifiziert",
    no_kyc_con2:
      "Bitte verifizieren Sie Ihre Identität, bevor Sie ein Zahlungskonto hinzufügen",

    no_kyc_confirm: "Zur Verifizierung",
    no_google_title: "Google Authenticator nicht gebunden",
    no_google_con1: "Ihr Google Authenticator ist noch nicht gebunden",
    no_google_con2:
      "Bitte binden Sie ihn zuerst, bevor Sie ein Zahlungskonto hinzufügen",

    no_google_confirm: "Zur Bindung",
    add_account_btn: "Zahlungskonto hinzufügen",
    delete_dialog_title: "Konto löschen",
    delete_dialog_con: "Möchten Sie dieses Zahlungskonto wirklich löschen?",
    delete_success: "Erfolgreich gelöscht",
    copy_address: "Zahlungsadresse erfolgreich kopiert",
    add_page_title: "Zahlungskonto hinzufügen",
    add_tab1: "Kryptowährung",
    add_tab2: "Bankkarte",
    add_subtitle_type: "Währung",
    add_subtitle_network: "Netzwerk",
    add_subtitle_address: "Adresse",
    add_address_placeholder:
      "Bitte geben Sie die Adresse der entsprechenden Währung ein",
    add_btn: "Speichern",
    add_subtitle_user_name: "Kontoinhaber",
    add_subtitle_status: "Verifiziert",
    add_subtitle_bank_name: "Bankname",
    add_bank_name_placeholder: "Bitte geben Sie den Banknamen ein",
    add_subtitle_card_number: "Kartennummer",
    add_bank_address_placeholder: "Bitte geben Sie die Kartennummer ein",
  },
  success_toast: {
    message: "Erfolgreich hinzugefügt",
  },
  home: {
    login: "Anmelden",
    loginDesc: "Melden Sie sich an, um Ihr Vermögen einzusehen",
    totalAssets: "Gesamtvermögen",
    fastTrading: "Schnellhandel",
    recharge: "Einzahlen",
    today: "Heute",
    index: "Index",
    hotSale: "Bestseller",
    marketRecommend: "Markt Empfehlungen",
    selfSelectedRecommend: "Selbst gewählte Empfehlungen",
    notification: "Benachrichtigungsinhalt Test, Test, Test...",
    optional: "Ausgewählt",
    homepage: "Startseite",
    market: "Markt",
    trade: "Handel",
    assets: "Vermögen",
    user: "Benutzer",
    market_trend: "Markttrends",
    ad_title: "Starten Sie Ihre Handelsreise",
    ad_con: "Schaffen Sie Ihren Weg zum Wohlstand",
    ad_btn: "Jetzt handeln",
    finance: "Finanzen",
  },
  assets: {
    recharge: "Einzahlen",
    withdraw: "Abheben",
    transfer: "Überweisen",
    financialRecords: "Finanzaufzeichnungen",
    header_total: "Gesamtvermögen",
    header_wallet: "Konto",
    header_order: "Bestellcenter",
    info_cash: "Bargeldkonto",
    info_order: "Positionen",
    over_view_cash: "Bargeldkonto",
    over_view_stock: "Aktien",
    over_view_contract: "Verträge",
    over_view_forex: "Devisen",
    over_view_trade: "Rohstoffe",
    wallet_header_cash: "Bargeldkonto",
    wallet_header_stock: "Aktienkonto",
    wallet_header_contract: "Vertragskonto",
    wallet_header_forex: "Devisenkonto",
    wallet_header_trade: "Rohstoffkonto",
    wallet_cash_balance: "Bargeldvermögen",
    wallet_stock_balance: "Aktienvermögen",
    wallet_contract_balance: "Vertragsvermögen",
    wallet_forex_balance: "Devisenvermögen",
    wallet_cash_value: "Bargeldkonto",
    wallet_forex_value: "Devisenkonto",
    wallet_stock_value: "Aktienvermögen",
    wallet_contract_value: "Vertragsvermögen",
    wallet_order_value: "Positionen",
    wallet_available: "Verfügbares Guthaben",
    wallet_blocked: "Gefrorenes Guthaben",
    wallet_available_sim: "Verfügbar",
    wallet_blocked_sim: "Eingefroren",
    wallet_handle_title: "Währungsoperationen",
    coin_list_recharge: "Einzahlen",
    coin_list_withdraw: "Abheben",
    coin_list_hide: "Verstecke Währungen mit Null-Bestand",
    coin_list_show: "Zeige Währungen mit Null-Bestand",
    safety_trade_pw: "Handelspasswort",
    safety_trade_placeholder: "Geben Sie das Handelspasswort ein",
    safety_trade_cancel: "Abbrechen",
    safety_trade_confirm: "Bestätigen",
    safety_trade_no_password: "Bitte Passwort eingeben",
    order_title_buy: "Kryptowährung kaufen",
    order_title_stock: "Aktien",
    order_title_contract: "Verträge",
    order_title_bot: "Handelsbot",
    order_title_ipo: "IPO",
    order_current_position: "Aktuelle Position",
    order_history: "Historische Anfragen",
  },
  withdraw: {
    withdraw: "Abheben",
    withdrawRecord: "Abhebeaufzeichnungen",
    cryptocurrency: "Kryptowährung",
    bankCard: "Bankkarte",
    currency: "Währung",
    network: "Netzwerk",
    confirm: "Bestätigen",
    currencySelection: "Währungswahl",
    networkSelection: "Netzwerkwahl",
    searchPlaceholder: "Suchen",
    addPaymentMethod: "Zahlungsmethode hinzufügen",
    withdrawable: "Abhebbar",
    withdrawalAmount: "Abhebungsbetrag",
    serviceFee: "Servicegebühr",
    receiptAccount: "Zahlungskonto",
    change: "Konto wechseln",
    accountSelection: "Kryptowährungskonto wählen",
    bankSelection: "Bankkonto wählen",
  },
  topUpCrypto: {
    recharge: "Einzahlen",
    rechargeRecord: "Einzahlungsaufzeichnungen",
    cryptocurrency: "Kryptowährung",
    bankCard: "Bankkarte",
    currency: "Währung",
    network: "Netzwerk",
    rechargeAmount: "Einzahlungsbetrag",
    inputPlaceholder: "Bitte eingeben",
    confirm: "Einzahlen",
    currencySelection: "Währungswahl",
    searchPlaceholder: "Suchen",
    enterCurrency: "Währung eingeben",
    networkSelection: "Netzwerkwahl",
    no_amount_msg: "Bitte Betrag eingeben",
    getting_rate_msg: "Wechselkurs wird abgerufen",
    no_enough_balance: "Unzureichendes Guthaben",
    no_account_msg: "Bitte fügen Sie ein Zahlungskonto hinzu",
    success_msg: "Aktion erfolgreich",
    no_auth_title: "Identitätsverifizierung",
    no_auth_con:
      "Sie haben Ihre Identität noch nicht verifiziert. Möchten Sie jetzt verifizieren?",
    no_google_msg: "Google Authenticator",
    no_google_con:
      "Ihr Google Authenticator ist noch nicht gebunden. Möchten Sie ihn jetzt binden?",
  },
  withdrawInfo: {
    title: "Abhebedetails",
    successful: "Abhebung erfolgreich",
    failed: "Abhebung fehlgeschlagen",
    failurePrompt:
      "Bitte versuchen Sie es erneut oder kontaktieren Sie den Kundensupport",
    processing: "Abhebung wird bearbeitet",
    processingTip: "Bitte warten Sie auf das Ergebnis der Abhebung",
    info_recharge_success_con1: "Ihr Abhebungsbetrag von",
    info_recharge_success_con2: "wurde erfolgreich überwiesen",
    withdrawalAmount: "Abhebungsbetrag",
    receivingAccount: "Zahlungskonto",
    withdrawalCurrency: "Abhebungswährung",
    withdrawalNetwork: "Abhebungsnetzwerk",
    orderNumber: "Bestellnummer",
    withdrawalTime: "Abhebungszeit",
  },
  recharging: {
    recharge: "Einzahlen",
    countdown: "Einzahlungs-Countdown",
    QRcodeExpired: "QR-Code ist abgelaufen",
    walletAddress: "Empfänger-Wallet-Adresse",
    copy: "Kopieren",
    tip1: "Hinweis: Bitte tätigen Sie die Einzahlung innerhalb der Frist",
    tip2: "Bestellung verfällt nach Ablauf",
    success: "Erfolgreich",
    fail: "Fehlgeschlagen",
    finish: "Abgeschlossen",
    info_title: "Einzahlungsdetails",
    info_recharge_success: "Einzahlung erfolgreich",
    info_recharge_success_con1: "Ihr eingezahlter Betrag von",
    info_recharge_success_con2: "wurde gutgeschrieben",
    info_recharge_failure: "Einzahlung fehlgeschlagen",
    info_recharge_failure_con:
      "Bitte versuchen Sie es erneut oder kontaktieren Sie den Kundensupport",
    info_recharge_pending: "Einzahlung wird bearbeitet",
    info_recharge_pending_con:
      "Bitte warten Sie auf das Ergebnis der Einzahlung",
    info_recharge_balance: "Einzahlungsbetrag",
    info_recharge_crpyto: "Einzahlungswährung",
    info_recharge_network: "Einzahlungsnetzwerk",
    info_recharge_address: "Einzahlungsadresse",
    info_recharge_order: "Bestellnummer",
    info_recharge_date: "Einzahlungszeit",
    copied: "Kopiert",
  },
  transfer: {
    transferRecord: "Überweisungsaufzeichnungen",
    page_title: "Überweisung",
    out: "Auszahlung",
    out_sim: "Auszahlen",
    out_amount: "Betrag eingeben",
    in: "Einzahlung",
    in_sim: "Einzahlen",
    in_amount: "Betrag eingeben",
    btn: "Überweisen",
    confirm: "Bestätigen",
    confirm_con: "Empfängerkonto",
    no_amount: "Bitte Betrag eingeben",
    no_enough_balance: "Unzureichendes Guthaben",
    account_same: "Keine Überweisung innerhalb desselben Kontos möglich",
    success: "Überweisung erfolgreich",
    transfer_map_money: "Bargeldkonto",
    transfer_map_stock: "Aktienkonto",
    transfer_map_futures: "Vertragskonto",
    transfer_map_forex: "Devisenkonto",
    transfer_map_trade: "Rohstoffkonto",
  },
  recordList: {
    financialRecords: "Finanzaufzeichnungen",
    rechargeRecord: "Einzahlungsaufzeichnungen",
    withdrawalRecord: "Abhebungsaufzeichnungen",
    transfer: "Überweisungsaufzeichnungen",
  },
  accountMap: {
    cashAccount: "Bargeldkonto",
    stockAccount: "Aktienkonto",
    contractAccount: "Vertragskonto",
    foreignExchangeAccount: "Devisenkonto",
  },
  topUpStatusMap: {
    review: "Einzahlung wird geprüft",
    success: "Einzahlung erfolgreich",
    failure: "Einzahlung fehlgeschlagen",
    unknown: "Einzahlung wird bearbeitet",
  },
  withdrawStatusMap: {
    review: "Abhebung wird bearbeitet",
    success: "Abhebung erfolgreich",
    failure: "Abhebung fehlgeschlagen",
    unknown: "Abhebung wird bearbeitet",
  },
  trade: {
    header_stock: "Aktien",
    header_contract: "Vertrag",
    header_aibot: "Handelsroboter",
    header_ipo: "IPO",
    header_forex: "Devisen",
    header_block: "Rohstoffe",
    header_block_long: "Rohstoffe",
    stock_open: "Position eröffnen",
    stock_position: "Position",
    stock_search: "Suche",
    stock_open_long: "Kaufen",
    stock_open_short: "Verkaufen",
    stock_open_long_tab: "Kaufen",
    stock_open_short_tab: "Verkaufen",
    stock_market_price: "Marktpreis",
    stock_limit_price: "Limitpreis",
    stock_take_stop: "Take Profit/Stop Loss",

    left_search: "Suche",
    left_mine: "Selbst ausgewählt",
    left_stock: "Aktien",
    left_contract: "Verträge",
    left_bot: "Handelsroboter",
    left_forex: "Devisen",
    left_all: "Alle",

    stock_opening_take: "Take Profit",
    stock_opening_stop: "Stop Loss",
    stock_opening_price: "Preis",
    stock_opening_price_market: "Marktpreis",
    stock_opening_price_limit: "Limitpreis",
    stock_opening_price_latest: "Letzter Preis",
    stock_opening_price_title: "Preis",
    stock_opening_price_tip: "Der Preis muss erreicht werden, um zu handeln",
    stock_opening_price_label: "Marktpreis",
    stock_opening_stock: "Aktien",
    contract_opening_contract: "Vertrag",
    stock_opening_amount_mode: "Margin-Modus",
    stock_opening_amount_limit_mode: "Limit-Modus",
    stock_opening_show_jump_type: "Übertragen/Umtauschen/Einzahlen",
    stock_opening_amount_title: "Menge",
    stock_opening_no_balance: "Nicht genügend Kontostand",
    stock_opening_enough_balance: "Guthaben",
    stock_opening_token_login: "Anmelden",
    stock_opening_token_register: "Registrieren",
    stock_opening_confirm_title: "Bestätigung der Positionseröffnung",
    stock_opening_amount: "Menge eröffnen",
    contract_opening_amount: "Vertragsmenge",
    stock_opening_no: "Nein",
    stock_opening_pay: "Zahlen",
    stock_opening_upfront: "Margin",
    stock_opening_fee: "Gebühr",
    stock_opening_trade_pw: "Handelskennwort",
    stock_opening_trade_pw_placeholder: "Geben Sie das Handelskennwort ein",
    stock_opening_confirm: "Bestätigen",
    stock_opening_search: "Suche",
    stock_opening_jump_mode1: "Übertragen",
    stock_opening_jump_mode2: "Übertragen",
    stock_opening_jump_mode3: "Übertragen",
    stock_opening_position_mode_cross: "Cross-Position",
    stock_opening_position_mode_isolated: "Isolierte Position",
    stock_account_balance: "Aktienkonto Guthaben",
    stock_account_notification:
      "Bitte laden Sie rechtzeitig auf oder übertragen Sie",
    stock_opening_btn_transfer: "Übertragen",
    stock_opening_btn_recharge: "Einzahlen",
    stock_opening_btn_trade: "Handeln",
    stock_opening_stop_price: "Preis",
    stock_opening_stop_amount: "Betrag",
    stock_opening_stop_ratio: "Prozentsatz",
    stock_opening_err_stock: "Wählen Sie Aktien aus",
    stock_opening_err_min_balance: "Mindesthandelgröße",
    stock_opening_err_price: "Geben Sie den Preis ein",
    stock_opening_err_take_price: "Geben Sie den Take Profit Preis ein",
    stock_opening_err_stop_price: "Geben Sie den Stop Loss Preis ein",
    stock_opening_err_limit: "Geben Sie den Limitpreis ein",
    stock_opening_success: "Position erfolgreich eröffnet",
    stock_opening_lever: "Hebel",
    stock_opening_closed: "Markt geschlossen, nicht handelbar",

    stock_position_stock: "Aktien/Status",
    stock_position_open: "Eröffnung/Verfügbar",
    stock_position_cost: "Aktueller Preis/Kosten",
    stock_position_profit: "Gewinn/Verlust",
    stock_position_close: "Position schließen",
    stock_position_close_order: "Schließen",
    stock_position_amount: "Menge",
    stock_position_ongoing_amount: "Offene Position",
    stock_position_all: "Alle",
    stock_position_btn: "Bestätigen",
    stock_position_update: "Bestellung aktualisieren",
    stock_position_add_deposit: "Margin hinzufügen",
    stock_position_no_close_amount: "Geben Sie die Menge zum Schließen ein",
    stock_position_success: "Erfolgreiche Operation",
    stock_position_no_deposit: "Geben Sie die Margin ein",
    stock_position_cancel_title: "Stornieren",
    stock_position_cancel_con:
      "Möchten Sie diese Bestellung wirklich stornieren?",
    stock_position_cancel_btn: "Abbrechen",
    stock_position_confirm_btn: "Bestätigen",
    stock_position_status_none: "Position eröffnet",
    stock_position_status_lock: "Gesperrt",
    stock_position_status_open: "Offene Position",
    stock_position_status_done: "Geschlossen",
    stock_position_status_fail: "Fehlgeschlagen",
    stock_position_status_cancel: "Abgebrochen",
    stock_position_offset_long: "Kaufen",
    stock_position_offset_short: "Verkaufen",
    stock_position_stop_price: "Preis",
    stock_position_stop_amount: "Betrag",
    stock_position_stop_ratio: "Prozentsatz",
    stock_position_unlogin_title: "Noch nicht eingeloggt?",
    stock_position_unlogin_con: "Jetzt anmelden",

    order_info_title_stock: "Aktienbestellung",
    order_info_title_contract: "Vertragsbestellung",
    order_info_available_stock: "Verfügbare Aktien",
    order_info_available_contract: "Verfügbare Vertragsmenge",
    order_info_profit: "Gewinn/Verlust",
    order_info_ratio: "Gewinn/Verlust Ratio",
    order_info_update: "Aktualisieren",
    order_info_cancel: "Stornieren",
    order_info_open_qty_contract: "Offene Menge (Verträge)",
    order_info_open_qty_other: "Offene Menge",
    order_info_stop_profit_price: "Take Profit Preis",
    order_info_stop_profit_amount: "Take Profit Betrag",
    order_info_stop_profit_ratio: "Take Profit Prozentsatz",
    order_info_stop_loss_price: "Stop Loss Preis",
    order_info_stop_loss_amount: "Stop Loss Betrag",
    order_info_stop_loss_ratio: "Stop Loss Prozentsatz",
    order_info_value: "Bestellwert",
    order_info_copy: "Kopiert",

    contract_position_no_close_amount: "Geben Sie die Menge zum Schließen ein",
    contract_position_ongoing_amount: "Offene Vertragsmenge",
    contract_position_cost: "Aktueller Preis/Kaufpreis",
    contract_opening_amount_title: "Vertragsmenge",
    contract_opening_order_value: "Bestellwert",
    contract_opening_err_contract: "Wählen Sie einen Vertrag",
    contract_opening_err_amount: "Geben Sie die Vertragsmenge ein",
    contract_create_guest_btn: "Registrieren Sie sich für ein Demo-Konto",
    contract_lots_amount: "Menge (Verträge)",
    contract_one_lot: "Vertrag",

    ai_opening_order: "Bestellung",
    ai_opening_trade: "Handel",
    ai_opening_long: "Kaufen",
    ai_opening_short: "Verkaufen",
    ai_opening_product_type: "Produktkategorie",
    ai_opening_time_zone: "Zeitzone",
    ai_opening_network_amount: "Netzwerkgröße",
    ai_opening_bigest_network: "Maximale Netzgröße",
    ai_opening_every_profit: "Profit pro Netzwerk",
    ai_opening_invest_amount: "Investitionsbetrag",
    ai_opening_balance: "Guthaben",
    ai_opening_login: "Anmelden",
    ai_opening_register: "Registrieren",
    ai_opening_confirm_order: "Bestellung bestätigen",
    ai_opening_predict_profit: "Voraussichtlicher Gewinn/Verlust",
    ai_opening_confirm_btn: "Bestätigen",
    ai_opening_ai_quantifi_list: "AI Quantifizierte Liste",
    ai_opening_cash_wallet: "Bargeldkonto",
    ai_opening_no_net: "Geben Sie die Netzgröße ein",
    ai_opening_no_product: "Wählen Sie ein Produkt aus",
    ai_opening_no_invest_amount: "Geben Sie den Investitionsbetrag ein",
    ai_opening_min_invest_amount: "Mindestinvestition",
    ai_opening_trade_password: "Geben Sie das Handelskennwort ein",
    ai_opening_success: "Position erfolgreich eröffnet",
    ai_opening_pop_title: "Konto Guthaben",
    ai_opening_pop_recharge: "Jetzt einzahlen",
    ai_opening_pop_transfer: "Jetzt überweisen",
    ai_opening_perform_time: "Laufzeit",
    ai_opening_historical_profit_rate: "Historische Rendite",
    ai_opening_24_profit_rate: "24 Stunden Rendite",
    ai_opening_profit_margin: "Gewinnmarge",
    ai_opening_profit_ratio: "Gewinn/Verlust Ratio",

    ai_position_title: "Bestelldetails",
    ai_position_profit: "Gewinn",
    ai_position_timer: "Abzählung",
    ai_position_end_trade: "Handelsende",
    ai_position_order_id: "Bestellnummer",

    ipo_title: "Bestellung",
    ipo_title_all: "Alle",
    ipo_title_pre: "Vorverkauf",
    ipo_title_going: "In der Zeichnung",
    ipo_title_finish: "Beendet",
    ipo_title_market: "Gelistet",
    ipo_detail_price: "Zeichnungspreis",
    ipo_detail_time: "Börsengangzeit",
    ipo_detail_date: "Zeichnungsdatum",
    ipo_detail_lever: "Zeichnungshebel",
    ipo_detail_listing_price: "Börsenkurs",
    ipo_detail: "IPO Details",
    ipo_opening_btn: "Zeichnen",
    ipo_detail_item1: "Aktiencode",
    ipo_detail_item2: "Zeichnungspreis",
    ipo_detail_item3: "Zeichnungsbeginn",
    ipo_detail_item4: "Zeichnungsende",
    ipo_detail_item5: "Börsengangdatum",
    ipo_detail_item6: "Börsenkurs",
    ipo_detail_item7: "Mindestzeichnungsmenge",
    ipo_detail_item8: "VIP Zeichnung",
    ipo_detail_item9: "Gebühren",
    ipo_detail_item10: "Zeichnungsmenge",
    ipo_detail_item11: "Markt",
    ipo_detail_item12: "Bestellwert",
    ipo_detail_item13: "Bestellmenge",
    ipo_detail_item14: "Eingefrorenes Kapital",
    ipo_detail_btn: "Zeichnen Sie ein",
    ipo_account_balance: "IPO Konto Guthaben",

    ipo_lottery_title1: "Alle",
    ipo_lottery_title2: "Warten auf Zuteilung",
    ipo_lottery_title3: "Zugewiesen",
    ipo_lottery_title4: "Nicht zugewiesen",
    ipo_lottery_title5: "Eingefroren",
    ipo_lottery_title6: "Zuteilung erhalten",
    ipo_lottery_amount: "Zuteilungsmenge",
    ipo_lottery_detail: "Zuteilungsdetails",
    ipo_leveraged_trading: "Margin Trading",
    ipo_sub_ordinary: "Ordentlich",
    ipo_sub_leveraged: "Hebel",
    ipo_sub_buy_code: "Zeichnungscode",
    ipo_sub_buy_no_amount: "Geben Sie die Zeichnungsmenge ein",
    ipo_sub_buy_no_code: "Geben Sie den Zeichnungscode ein",
    ipo_success_title: "Zeichnung Erfolgreich",
    ipo_success_con:
      "Herzlichen Glückwunsch zum erfolgreichen Zeichnen, bitte warten Sie geduldig auf die Zuteilungsinformationen",
    ipo_success_btn1: "Weiter zeichnen",
    ipo_success_btn2: "Bestelldetails",

    ipo_detail_title: "Bestelldetails",
    ipo_detail_loading: "Lädt",
    ipo_detail_status_success: "Herzlichen Glückwunsch, zugewiesen",
    ipo_detail_status_wait: "Zeichnung abgeschlossen, warten auf Zuteilung",
    ipo_detail_status_failure: "Leider, nicht zugewiesen",
    ipo_detail_order_no: "Bestellnummer",
    ipo_detail_win_num: "Zugewiesene Menge",
    ipo_detail_buy_num: "Zeichnungsmenge",
    ipo_detail_block_num: "Eingefrorenes Kapital",
    ipo_detail_buy_value: "Zeichnungsbetrag",
    ipo_detail_fee: "Gebühr",
    ipo_detail_leverage: "Zeichnungshebel",
    ipo_detail_market_date: "Börsengangdatum",
    ipo_detail_market_price: "Börsenpreis",
    ipo_detail_buy_price: "Zeichnungspreis",
    ipo_detail_buy_date: "Zeichnungsdatum",
    ipo_detail_order_date: "Bestelldatum",

    forex_opening_title: "Devisen",
    forex_position_title: "Devisen/Status",
    trade_order_history: "Historische Bestellungen",

    left_search_result: "Suchergebnisse",
  },
  inviteFriends: {
    invite: "Freunde einladen",
    reward: "Meine Belohnungen",
    banner_title: "Freunde einladen und erhalten",
    banner_desc: "Lade Freunde ein und verdiene gemeinsam",
    qrcode_title: "Einladungs-QR-Code",
    save_img: "Bild speichern",
    img_name: "Mein QR-Code",
    invite_code: "Einladungscode",
    copy: "Kopieren",
    copy_success: "Erfolgreich kopiert",
    url_title: "Einladungslink",
    copy_url: "Link kopieren",
    performance_title: "Empfehlungsleistung",
    details: "Empfehlungsdetails",
    user: "Benutzer",
    performance: "Leistung",
  },
  market: {
    market_header_optional: "Meine Auswahl",
    market_header_buy: "Krypto kaufen",
    market_header_stock: "Aktien",
    market_header_contract: "Derivate",
    market_header_ai: "Trading-Bot",
    market_header_forex: "Forex",

    market_optional_add: "Zur Auswahl hinzufügen",
    market_optional_no_optional: "Du hast noch keine Auswahl hinzugefügt",
    market_optional_add_all: "Alle zur Auswahl hinzufügen",
    market_optional_recommend_stock: "Empfohlene Aktien",
    market_optional_recommend_crypto: "Empfohlene Kryptowährungen",
    market_optional_add_success: "Erfolgreich hinzugefügt",
    market_optioanl_del_success: "Erfolgreich entfernt",

    market_optional_crypto_price: "Letzter Preis",
    market_optional_short: "Preisänderung",
    market_optioanl_ratio: "Preisänderung in %",
    market_optional_stock: "Aktien",
    market_optional_contract: "Kryptowährungen",
    market_optional_forex: "Forex",
    market_optional_blocktrade: "Rohstoffe",

    market_marketinfo_data: "Daten",
    market_marketinfo_trade: "Handel",
    market_marketinfo_long: "Kauf (Long)",
    market_marketinfo_short: "Verkauf (Short)",
    market_marketinfo_open: "Eröffnung",
    market_marketinfo_high: "Höchstpreis",
    market_marketinfo_amount: "Volumen",
    market_marketinfo_close: "Schlusskurs",
    market_marketinfo_low: "Tiefstpreis",
    market_marketinfo_value: "Gesamtwert",

    market_buy_title1: "Schnellbereich",
    market_buy_title2: "Meine Auswahl",
    market_buy_title3: "Bestellung",
    market_buy_fast_buy: "Kaufen",
    market_buy_fast_sell: "Verkaufen",
    market_buy_fast_buy_btn: "Kaufen",
    market_buy_fast_sell_btn: "Verkaufen",
    market_buy_fast_receive: "Erhalten",
    market_buy_fast_receive_sim: "Erhalten",
    market_buy_fast_pay: "Bezahlen",
    market_buy_fast_estprice: "Geschätzter Preis",
    market_buy_fast_search_title: "Währungsauswahl",
    market_buy_fast_search_input: "Währung eingeben",
    market_buy_fast_no_amount: "Bitte Betrag eingeben",
    market_buy_fast_noti_title: "Hinweis",
    market_buy_fast_noti_con:
      "Unzureichendes Wallet-Guthaben, bitte aufladen oder Geld überweisen",
    market_buy_fast_noti_cancel: "Zur Aufladung",
    market_buy_fast_noti_confirm: "Zur Überweisung",
    market_buy_fast_success: "Bestellung erfolgreich",
    market_buy_fast_account_title: "Kontenauswahl",
    market_buy_fast_account_crypto: "Kryptowährung",
    market_buy_fast_account_bank: "Bankkonto",
    market_buy_fast_account_add: "Zahlungskonto hinzufügen",
    market_buy_optional_deal: "Handelsvolumen",
    market_buy_optional_rate: "Erfolgsquote",
    market_buy_optional_duaration: "Dauer (Minuten)",
    market_buy_optional_order_limit: "Bestelllimit",
    market_buy_optional_buy: "Kaufen",
    market_buy_optional_sell: "Verkaufen",
    market_buy_optional_estreceive: "Voraussichtlicher Erhalt",
    market_buy_optional_limit_val: "Limit",
    market_buy_optional_confirm: "Bestätigen",

    market_buy_list_buy: "Kaufen",
    market_buy_list_sell: "Verkaufen",
    market_buy_list_price: "Preis",
    market_buy_list_amount: "Menge",
    market_buy_list_wait_pay: "Warten auf Zahlung",
    market_buy_list_wait_confirm: "Warten auf Bestätigung",
    market_buy_list_wait_pay1: "Warten auf Zahlung",
    market_buy_list_wait_confirm1: "Warten auf Bestätigung",
    market_buy_list_complete: "Handel abgeschlossen",
    market_buy_list_cancel: "Handel abgebrochen",
    market_buy_list_contact: "Händler kontaktieren",
    market_buy_list_wait_buyer_confirm: "Warten auf Käuferbestätigung",
    market_buy_list_wait_buyer_con:
      "Bitte überweisen Sie den Gesamtbetrag auf das vom Händler angegebene Bankkonto",
    market_buy_list_wait_con: "Zahlung erfolgt, warten auf Händlerbestätigung",
    market_buy_list_wait_result:
      "Händler hat gezahlt, bitte überprüfen Sie, ob das Geld eingegangen ist",
    market_buy_list_wait_buyer_bank: "Warten auf Bankkontodaten des Händlers",
    market_buy_list_wait_bank_no: "Kontonummer",
    market_buy_list_wait_account: "Konto",
    market_buy_list_wait_total: "Gesamtbetrag",
    market_buy_list_wait_price: "Preis",
    market_buy_list_wait_amount: "Menge",
    market_buy_list_cancel_order: "Bestellung stornieren",
    market_buy_list_paid: "Ich habe bezahlt",
    market_buy_list_received: "Ich habe erhalten",
    market_buy_list_trade_sccess: "Handel abgeschlossen",
    market_buy_list_paid_success: "Zahlung erfolgreich",
    market_buy_list_pass_success: "Freigabe erfolgreich",
    market_buy_list_cancel_success: "Stornierung erfolgreich",
    market_buy_list_pre_pay: "Voraussichtliche Zahlung",
    market_buy_list_firt_select:
      "Bitte fügen Sie zuerst ein Zahlungskonto hinzu",
    market_buy_chat_con1: "Sie haben erfolgreich bestellt",
    market_buy_chat_con2:
      "Bitte warten Sie geduldig auf die Zahlung des Händlers",

    market_stock_country_us: "Vereinigte Staaten",
    market_stock_country_japan: "Japan",
    market_stock_country_india: "Indien",
    market_stock_country_korea: "Korea",
    market_stock_country_germany: "Deutschland",
    market_stock_country_uk: "Vereinigtes Königreich",
    market_stock_country_singapore: "Singapur",
    market_stock_country_hongkong: "Hongkong",
    market_stock_country_malaysia: "Malaysia",
    market_stock_country_us_long: "Vereinigte Staaten",
    market_stock_country_japan_long: "Japan",
    market_stock_country_india_long: "Indien",
    market_stock_country_korea_long: "Korea",
    market_stock_country_germany_long: "Deutschland",
    market_stock_country_uk_long: "Vereinigtes Königreich",
    market_stock_country_singapore_long: "Singapur",
    market_stock_country_hongkong_long: "Hongkong",
    market_stock_country_malaysia_long: "Malaysia",
    market_stock_updatetime: "Aktualisierungszeit",
    market_stock_description_title: "Preisänderung",
    market_stock_description_des1: "Erhöhung",
    market_stock_description_des2: "Abnahme",
    market_stock_description_long_end: "Preisanstieg",
    market_stock_description_center: "Neutral",
    market_stock_description_short_end: "Preisrückgang",
    market_stock_chase_movement: "Preisanstieg nachverfolgen",
    market_stock_chase_earning_effect: "Gewinnwirkung",
    market_stock_chase_strong: "Stark",
    market_stock_chase_movement_percentage: "Preisveränderung im Vergleich",
    market_stock_chase_todays_effect: "Preisanstieg heute",
    market_stock_chase_long_sort: "Top-Aufsteiger",
    market_stock_chase_short_sort: "Top-Absteiger",
    market_stock_hot: "Beliebte Aktien",
    market_ai_title1: "Standard",
    market_ai_title2: "Historisch hohe Renditen",
    market_ai_title3: "24 Stunden hohe Renditen",
    market_ai_title4: "Hoher Hebel",
    market_search_title: "Suche",
    market_search_history: "Suchverlauf",
    market_search_recommend: "Empfohlene Suchen",
    market_search_des: "Mehr als 20.000 Nutzer suchen",

    market_buy_confirm_coin: "Bestellbestätigung",
    market_buy_will_pay: "Du wirst bezahlen",
    market_buy_will_sell: "Du wirst verkaufen",
    market_buy_will_receive: "Du wirst erhalten",

    market_faster_available: "Verfügbares Guthaben",
    market_already_done: "Bereits erledigt",
    market_already_cancel: "Bereits abgebrochen",

    market_order_details_wait: "Warten",
    market_order_details_for_buyer: "Warten auf Zahlung des Käufers",
    market_order_details_for_seller: "Warten auf Bestätigung des Verkäufers",
    market_order_details_con1: "Bitte überweisen Sie den Gesamtbetrag",
    market_order_details_con2: "auf das vom Händler angegebene Bankkonto",
  },
  finance: {
    portfolio: "Finanzanlage",
    portfolio_menu: "Portfolio",
    portfolio_title: "Staking Mining",
    portfolio_order: "Bestellungen",
    portfolio_revenue: "Gesamtgewinn",
    portfolio_investment_amt: "Investitionsbetrag",
    portfolio_yield: "Rendite",
    portfolio_duration: "Dauer",
    portfolio_participate: "Beteiligen",
    portfolio_hot: "HOT",
    portfolio_day: "Tag",
    portfolio_day_multi: "Tage",
    portfolio_mining_title: "Staking Mining",
    portfolio_mining_subTitle1: "Abonnement-Portfolio",
    portfolio_mining_subTitle2: "Abonnement-Betrag",
    portfolio_mining_operation: "Betriebsdauer",
    portfolio_mining_revenue: "Geschätzter Gewinn",
    portfolio_mining_investment: "Investitionsbetrag",
    portfolio_mining_fee: "Gebühren",
    portfolio_mining_header: "Abonnementbetrag",
    portfolio_mining_balance: "Kontostand",
    portfolio_mining_placeholder: "Bitte Investitionsbetrag eingeben",
    portfolio_mining_btn: "Abonnieren",
    portfolio_mining_title3: "Wie funktioniert es?",
    portfolio_mining_guide:
      "Es werden eine Reihe von Börsen integriert, wie Coinbase, Huobi, Binance, KuCoin, YFX und andere bekannte globale Börsen. Durch Algorithmen werden die Trends verschiedener Kryptowährungen erkannt, und der aktuelle Markt wird überwacht. Innerhalb eines bestimmten Preisrahmens wird häufig gekauft und verkauft, um Arbitrage zu betreiben und so die Rendite zu maximieren.",
    portfolio_mining_noti: "Hinweis",
    portfolio_mining_noti_duration: "Betriebsdauer",
    portfolio_mining_noti_daily: "Tägliche Rendite",
    portfolio_mining_noti_est: "Geschätzter Gewinn",
    portfolio_mining_noti_investment: "Investitionsbetrag",
    portfolio_mining_noti_fee: "Gebühren",
    portfolio_order_title: "Investitionsbestellungen",
    portfolio_order_tab1: "Laufend",
    portfolio_order_tab2: "Abgeschlossen",
  },
  copy: {
    title: "Kopieren",
    copy_option: "Kopieren",
    copy_trade: "Handel",
    total_revenue: "Gewinn",
    level: "{level} Stufe",
  },
};
