
export default {
    
    assets:{
        recharge:"充值",
        withdraw:"提现",
        transfer:"划转",
        financialRecords:"资金记录"
    },
    topUpCrypto:{
        recharge:"充值",
        rechargeRecord:"充值记录",
        cryptocurrency:"加密货币",
        bankCard:"银行卡",
        currency:"币种",
        network:"网络",
        rechargeAmount:"充值金额",
        inputPlaceholder:"请输入",
        confirm:"确定",
        currencySelection:"币种选择",
        searchPlaceholder:"搜索",
        enterCurrency:"输入币种",
        networkSelection:"网络选择"
    },
    withdraw:{
        withdraw:"提现",
        withdrawRecord:"提现记录",
        cryptocurrency:"加密货币",
        bankCard:"银行卡",
        currency:"币种",
        network:"网络",
        confirm:"确定",
        currencySelection:"币种选择",
        searchPlaceholder:"搜索",
    },
    recharging:{
        recharge:"充值",
        countdown:"充值倒计时",
        QRcodeExpired:"二维码已过期",
        walletAddress:"收款人钱包地址",
        copy:"复制",
        tip1:'提示：请在截至时间内完成充值',
        tip2:'订单到期作废',
        success:"成功",
        fail:'失败',
        finish:'完成'

    },
    transfer:{
        transferRecord:"划转记录"
    }
}