export default {
  login: {
    login: "登錄",
    email: "郵箱",
    phone: "手機",
    phone_number: "手機號",
    password: "密碼",
    forget_pw: "忘記密碼?",
    country_number: "輸入區號",
    pw_placeholder1: "您的郵箱",
    pw_placeholder2: "您的手機號",
    pw_placeholder3: "請輸入您的密碼",
    pw_placeholder4: "區號選擇",
    no_account_con1: "沒有賬號嗎？",
    no_account_con2: "去註冊",
    no_account_warning: "賬號不存在",
    login_success: "登錄成功",
    login_failed: "登錄異常",
    network_error: "網絡異常",
  },
  register: {
    security: "安全驗證",
    security_con: "拖動滑塊，使圖片角度為正",
    security_result_success: "驗證成功",
    security_result_failed: "驗證失敗",
    security_result_pedding: "待滑動驗證",
  },
  user_page: {
    login_out: "註冊/登錄",
    recommended_user: "推薦用戶",
    social_user: "網絡用戶",
    recommend_bonus: "推薦獎金",
    ad_head: "領取投資模擬金",
    ad_con1: "模擬投資",
    ad_con2: "收益在售",
    receive_payment: "收款賬戶",
    verify_identity: "身份認證",
    google_verification: "谷歌驗證器",
    already_verified: "已認證",
    pending_verified: "待處理",
    not_verified: "未認證",
    already_set: "已綁定",
    not_set: "未綁定",
    recommend_friend: "推薦好友",
    set_language: "語言",
    security: "安全",
    about: "關於",
    logout: "退出登錄",
    already_set_google: "谷歌驗證器已綁定",
    not_set_google_yet: "谷歌驗證器未綁定",
    message_box_con: "您當前確定要退出嗎",
    message_box_confirm: "取消",
    message_box_cancel: "確認",
  },
  form: {
    all: "全部",
  },
  assets: {
    recharge: "充值",
    withdraw: "提現",
    transfer: "劃轉",
    financialRecords: "資金記錄",
  },
  topUpCrypto: {
    recharge: "充值",
    rechargeRecord: "充值記錄",
    cryptocurrency: "加密代幣",
    bankCard: "銀行卡",
    currency: "幣種",
    network: "網絡",
    rechargeAmount: "充值金額",
    inputPlaceholder: "請輸入",
    confirm: "確定",
    currencySelection: "幣種選擇",
    searchPlaceholder: "搜索",
    enterCurrency: "輸入幣種",
    networkSelection: "網絡選擇",
  },
  withdraw: {
    withdraw: "提現",
    withdrawRecord: "提現記錄",
    cryptocurrency: "加密代幣",
    bankCard: "銀行卡",
    currency: "幣種",
    network: "網絡",
    confirm: "確定",
    currencySelection: "幣種選擇",
    networkSelection: "網絡選擇",
    searchPlaceholder: "搜索",
    addPaymentMethod: "添加收款方式",
    withdrawable: "可提現",
    withdrawalAmount: "提現金額",
    serviceFee: "手續費",
    receiptAccount: "收款賬戶",
    change: "更改",
    accountSelection: "加密代幣賬號選擇",
    bankSelection: "銀行卡賬號選擇",
  },
  withdrawInfo: {
    title: "提現詳情",
    successful: "提現成功",
    failed: "提現失敗",
    failurePrompt: "聽重新提現，或重新聯繫客服",
    processing: "提現處理中",
    processingTip: "請等待提現結果",
    withdrawalAmount: "提現金額",
    receivingAccount: "收款賬戶",
    withdrawalCurrency: "提現幣種",
    withdrawalNetwork: "提現網絡",
    orderNumber: "訂單編號",
    withdrawalTime: "提現時間",
  },
  recharging: {
    recharge: "充值",
    countdown: "充值倒計時",
    QRcodeExpired: "二維碼已過期",
    walletAddress: "收款人錢包地址",
    copy: "複製",
    tip1: "提示：請在截止時間內完成充值",
    tip2: "訂單到期作廢",
    success: "成功",
    fail: "失敗",
    finish: "完成",
  },
  transfer: {
    transferRecord: "劃轉記錄",
  },
  recordList: {
    financialRecords: "資金記錄",
    rechargeRecord: "充值記錄",
    withdrawalRecord: "提現記錄",
    transfer: "計劃記錄",
  },
  accountMap: {
    cashAccount: "現金賬戶",
    stockAccount: "股票賬戶",
    contractAccount: "合約賬戶",
    foreignExchangeAccount: "外匯賬戶",
  },
  topUpStatusMap: {
    review: "充值審核中",
    success: "充值成功",
    failure: "充值失敗",
    unknown: "充值處理中",
  },
  withdrawStatusMap: {
    review: "提現審核中",
    success: "提現成功",
    failure: "提現失敗",
    unknown: "提現處理中",
  },
};
