export default {
  common: {
    stock: "주식",
    crypto: "계약",
    AI: "AI",
    IPO: "상장",
    closed: "마감",
    no_data: "데이터 없음",
    day: "일",
    min: "분",
    no_more: "더 이상 없습니다",
    no_wallet: "수금 계좌 없음",
    spot: "현물",
    option: "옵션",
    second: "초",
    hour: "시간",

  },
  login: {
    login: "로그인",
    email: "이메일",
    phone: "휴대폰",
    phone_number: "휴대폰 번호",
    password: "비밀번호",
    forget_pw: "비밀번호를 잊으셨나요?",
    country_number: "국가 번호 선택",
    pw_placeholder1: "이메일을 입력하세요",
    pw_placeholder2: "휴대폰 번호를 입력하세요",
    pw_placeholder3: "비밀번호를 입력하세요",
    pw_placeholder4: "국가 번호를 입력하세요",
    no_account_con1: "계정이 없으신가요?",
    no_account_con2: "회원가입",
    no_account_warning: "계정이 존재하지 않습니다",
    login_success: "로그인 성공",
    login_failed: "로그인 실패",
    network_error: "네트워크 오류",
  },
  forget_pw: {
    title: "비밀번호 찾기",
    email_phone: "이메일/휴대폰 번호",
    success: "비밀번호가 재설정되었습니다",
    back: "로그인 화면으로 돌아가기",
    get_back: "비밀번호 찾기",
  },
  register: {
    security: "보안 인증",
    security_con: "슬라이더를 드래그하여 이미지 각도를 맞추세요",
    security_result_success: "인증 성공",
    security_result_failed: "인증 실패",
    security_result_pending: "슬라이더 인증 대기 중",
    security_result_move: "슬라이딩 인증 중",
    create_user_account: "회원 가입",
    create_guest_account: "게스트 계정 만들기",
    has_account: "계정이 있나요?",
    go_login: "로그인하기",
    email: "이메일",
    phone: "휴대폰",
    phone_number: "휴대폰 번호",
    login_password: "로그인 비밀번호",
    trade_password: "거래 비밀번호",
    forget_pw: "비밀번호를 잊으셨나요?",
    country_number: "국가 번호 선택",
    pw_placeholder1: "이메일을 입력하세요",
    pw_placeholder2: "휴대폰 번호를 입력하세요",
    pw_placeholder3: "최소 8자 이상 비밀번호",
    pw_placeholder4: "국가 번호 입력",
    pw_placeholder5: "거래 비밀번호를 입력하세요",
    pw_placeholder6: "초대 코드를 입력하세요",
    invite_code: "초대 코드",
    agree_con1: "저는",
    agree_con2: "개인정보 처리방침",
    agree_con3: "및",
    agree_con4: "이용약관에 동의합니다",
    register_success: "회원 가입 성공",
    register_failed: "가입 오류",
    next: "다음",
    code_email: "이메일",
    code_phone: "휴대폰",
    code_verify: "인증",
    code_con1: "인증 코드를",
    code_con2: "로 전송했습니다",
    code_jump: "인증 건너뛰기",
    code_again: "다시 보내기",
    code_jump_title: "인증을 건너뛰면 등록이 계속됩니다. 계속 하시겠습니까?",
    code_jump_confirm: "확인",
    success_sign_up: "가입 완료",
    success_btn: "이중 인증 & 신원 인증",
    success_finish: "완료",
    no_email_error: "유효한 이메일을 입력하세요",
    no_phone_error: "휴대폰 번호를 입력하세요",
    no_login_pw_error: "비밀번호를 입력하세요",
    login_pw_length_error: "비밀번호는 최소 8자 이상이어야 합니다",
    no_trade_pw_error: "거래 비밀번호를 입력하세요",
    no_agree_error: "개인정보 처리방침 및 이용약관에 동의해 주세요",
    network_error: "네트워크 오류, 다시 시도해 주세요",
    guest_account: "게스트 계정",
    already_get_virtual: "가상 자금이 입금되었습니다",
    user_already_exist: "이미 등록된 사용자입니다",
    enter_graphic_number: "이미지 인증 번호를 입력하세요",
    not_clear: "잘 보이지 않나요? 새로 고침",
    enter_verify_code: "인증 코드를 입력하세요",
    verify_code_error: "인증 코드 받기 오류, 수동으로 새로 고침 해주세요",
  },
  password_level: {
    weak: "약함",
    normal: "보통",
    strong: "강함",
  },
  code_input: {
    btn_text1: "계속",
    btn_text2: "연결",
  },
  user_page: {
    login_out: "회원가입/로그인",
    recommended_user: "추천 사용자",
    social_user: "네트워크 사용자",
    recommend_bonus: "추천 보너스",
    ad_head: "투자 가상 자금 받기",
    ad_head1: "회원가입 즉시 보상 받기",
    ad_con3: "1000USDT",
    ad_con1: "가상 투자",
    ad_con2: "수익 판매 중",
    receive_payment: "수취 계좌",
    verify_identity: "신원 인증",
    google_verification: "구글인증기",
    already_verified: "인증 완료",
    pending_verified: "인증 대기 중",
    not_verified: "인증안됨",
    already_set: "이미 연결됨",
    not_set: "연결안됨",
    recommend_friend: "친구 추천",
    set_language: "언어 설정",
    security: "보안",
    about: "소개",
    logout: "로그아웃",
    already_set_google: "구글 인증기 연결됨",
    not_set_google_yet: "구글 인증기 연결 안 됨",
    message_box_con: "정말 로그아웃 하시겠습니까?",
    message_box_confirm: "확인",
    message_box_cancel: "취소",
    get_demo_coin: "받으러 가기",

    manage_assets: "자산 관리",
    user_func: "사용자 기능",
    support: "고객 지원",
    news: "뉴스",
    setting: "개인 설정",
  },
  kyc: {
    page_title: "신원 인증",
    first_basic_info: "기본 정보",
    first_upload_card: "증명서 업로드",
    first_title: "신원 인증을 진행하세요",
    first_description:
      "금융 규정에 따라, 정부에서 발급한 신분증과 일치하는지 확인해야 합니다.",
    first_legal_name: "법적 이름",
    first_card_id: "증명서 번호",
    first_birthday: "생년월일",
    first_birthday_placeholder: "생년월일을 선택하세요",
    first_btn: "다음",
    first_confirm: "확인",
    second_basic_info: "기본 정보",
    second_upload_card: "증명서 업로드",
    second_title: "증명서 업로드",
    second_description: "본인 인증을 위해 증명서를 업로드해 주세요.",
    second_card_front: "증명서 앞면",
    second_card_back: "증명서 뒷면",
    second_card_hand: "증명서를 들고 있는 사진",
    second_upload_rule: "업로드 요구 사항",
    second_upload_description:
      "증명서의 테두리가 완전하고, 글자가 선명하며, 밝기가 균일한지 확인해 주세요.",
    second_standard_img: "표준 촬영",
    second_failed1: "촬영이 불완전함",
    second_failed2: "촬영이 흐림",
    second_failed3: "플래시 과다",
    second_btn: "완료",
    final_title: "신원 인증 제출 완료",
    final_description:
      "심사 결과를 기다려 주세요. 신원 정보는 엄격히 비밀로 처리됩니다.",
    final_ok: "확인",
    status_success: "인증 성공",
    status_pending: "심사 중",
    status_pending_description:
      "신원 인증이 제출되었습니다. 결과를 기다려 주세요.",
    status_failure: "인증 실패",
    status_card_no: "증명서 번호",
    status_birthday: "생년월일",
    status_reverify: "다시 인증하기",
    status_service: "고객 서비스에 문의",
    verify_success: "심사 통과",
    verify_failure: "심사 실패",
    id_photo_requirement: "사진 업로드 요구 사항",
  },
  google_auth: {
    page_title: "구글 인증기",
    from_register_skip: "건너뛰기",
    google_title: "구글 인증기 연결",
    bound_success: "연결 성공",
    copy_success: "복사 성공",
    confirm_title: "구글 인증기 연결을 건너뛰시겠습니까?",
    google_result_title: "연결됨",
    google_result_con: "문제가 있으시면 온라인 고객 서비스에 문의하세요",
    google_result_btn: "확인",
    google_input_title: "구글 인증 코드",
    google_input_con: "6자리 코드를 입력하세요",
    google_input_btn_cancel: "취소",
    google_input_btn_confirm: "확인",
  },
  service: {
    page_title: "고객 서비스",
    message_title: "고객 서비스가 도와드리겠습니다",
    first_message: "안녕하세요, 무엇을 도와드릴까요?",
    input_message: "입력해 주세요...",
  },
  language: {
    page_title: "언어 선택",
  },
  safety: {
    page_title: "보안",
    change_login_pw: "로그인 비밀번호",
    change_trade_pw: "거래 비밀번호",
    bind_google_auth: "구글 인증기",
    google_status_not: "미연결",
    google_status_ok: "연결됨",
    no_google_dialog_title: "구글 인증기",
    no_google_dialog_con:
      "구글 인증기를 아직 연결하지 않으셨습니다. 연결하시겠습니까?",
    success_title: "작업 성공",
    success_btn: "닫기",
  },
  change_login_pw: {
    page_title: "로그인 비밀번호 변경",
    origin_pw: "현재 비밀번호",
    origin_pw_placeholder: "현재 비밀번호를 입력하세요",
    new_pw: "새 비밀번호",
    new_pw_placeholder: "비밀번호는 최소 8자 이상",
    confirm_pw: "새 비밀번호 확인",
    confirm_pw_placeholder: "새 비밀번호를 다시 입력하세요",
    btn: "변경",
    no_match_noti: "비밀번호가 일치하지 않습니다",
  },
  change_trade_pw: {
    page_title: "거래 비밀번호 변경",
    origin_pw: "현재 비밀번호",
    origin_pw_placeholder: "현재 비밀번호를 입력하세요",
    new_pw: "새 비밀번호",
    new_pw_placeholder: "비밀번호는 최소 8자 이상",
    confirm_pw: "새 비밀번호 확인",
    confirm_pw_placeholder: "새 비밀번호를 다시 입력하세요",
    btn: "변경",
    no_match_noti: "비밀번호가 일치하지 않습니다",
  },
  account: {
    page_title: "출금 주소",
    crypto: "암호화폐",
    no_data: "수금 계좌가 없습니다",
    bank: "은행 계좌",
    no_kyc_title: "신원 미인증",
    no_kyc_con1: "당신의 신원이 인증되지 않았습니다",
    no_kyc_con2: "인증 후 수금 계좌를 추가해 주세요",

    no_kyc_confirm: "인증하러 가기",
    no_google_title: "구글 인증기 미연결",
    no_google_con1: "구글 인증기가 아직 연결되지 않았습니다",
    no_google_con2: "연결 후 수금 계좌를 추가해 주세요",

    no_google_confirm: "연결하러 가기",
    add_account_btn: "수금 계좌 추가",
    delete_dialog_title: "계좌 삭제",
    delete_dialog_con: "이 수금 계좌를 삭제하시겠습니까?",
    delete_success: "삭제 성공",
    copy_address: "결제 주소 복사 성공",
    add_page_title: "수금 계좌 추가",
    add_tab1: "암호화폐",
    add_tab2: "은행 계좌",
    add_subtitle_type: "화폐 종류",
    add_subtitle_network: "네트워크",
    add_subtitle_address: "주소",
    add_address_placeholder: "해당 화폐 주소를 입력하세요",
    add_btn: "저장",
    add_subtitle_user_name: "카드 소지자 이름",
    add_subtitle_status: "인증됨",
    add_subtitle_bank_name: "은행 이름",
    add_bank_name_placeholder: "은행 이름을 입력하세요",
    add_subtitle_card_number: "카드 번호",
    add_bank_address_placeholder: "은행 계좌 번호를 입력하세요",
  },
  success_toast: {
    message: "추가 성공",
  },
  home: {
    login: "로그인",
    loginDesc: "로그인 후 자산을 확인할 수 있습니다",
    totalAssets: "총 자산",
    fastTrading: "빠른 거래",
    recharge: "충전",
    today: "오늘",
    index: "지수",
    hotSale: "핫 세일",
    marketRecommend: "시장 추천",
    selfSelectedRecommend: "직접 선택한 추천",
    notification: "공지사항 내용 테스트 테스트 테스트...",
    optional: "자기 선택",
    homepage: "홈",
    market: "시장",
    trade: "거래",
    assets: "자산",
    user: "사용자",
    market_trend: "시장 트렌드",
    ad_title: "당신의 거래 여정을 시작하세요",
    ad_con: "부의 길을 창조하세요",
    ad_btn: "거래 시작",
    finance: "재테크",
    news: "뉴스",
    simulatedTradingTitle: "가상 금 획득",
    simulatedTradingButton: "가상 거래",

    secure: "안전",
    convinient: "편리",
    reliable: "엄격",
    landing_con1: "수천만 사용자",
    landing_con2: "모두가 사용하는",
    landing_con3: "거래소",
    landing_con4: "무한한 가능성을 경험하세요",
    landing_more: "더 많은",

  },
  assets: {
    recharge: "충전",
    withdraw: "출금",
    transfer: "이체",
    financialRecords: "자금 기록",
    header_total: "총 자산",
    header_wallet: "계좌",
    header_order: "주문 센터",
    info_cash: "현금 계좌",
    info_order: "보유 금액",
    over_view_cash: "현금 계좌",
    over_view_stock: "주식",
    over_view_contract: "계약",
    over_view_forex: "외환",
    over_view_trade: "원자재",
    wallet_header_cash: "현금 계좌",
    wallet_header_stock: "주식 계좌",
    wallet_header_contract: "계약 계좌",
    wallet_header_forex: "외환 계좌",
    wallet_header_trade: "원자재 계좌",
    wallet_cash_balance: "현금 자산",
    wallet_stock_balance: "주식 자산",
    wallet_contract_balance: "계약 자산",
    wallet_forex_balance: "외환 자산",
    wallet_cash_value: "현금 계좌",
    wallet_forex_value: "외환 계좌",
    wallet_stock_value: "주식 잔액",
    wallet_contract_value: "계약 잔액",
    wallet_order_value: "보유 금액",
    wallet_available: "사용 가능 금액",
    wallet_blocked: "동결 금액",
    wallet_available_sim: "사용 가능",
    wallet_blocked_sim: "동결",
    wallet_handle_title: "화폐 단위 작업",
    coin_list_recharge: "충전",
    coin_list_withdraw: "출금",
    coin_list_hide: "잔액이 0인 화폐 숨기기",
    coin_list_show: "잔액이 0인 화폐 표시",
    safety_trade_pw: "거래 비밀번호",
    safety_trade_placeholder: "거래 비밀번호를 입력하세요",
    safety_trade_cancel: "취소",
    safety_trade_confirm: "확인",
    safety_trade_no_password: "비밀번호를 입력하세요",
    order_title_buy: "구매",
    order_title_stock: "주식",
    order_title_contract: "계약",
    order_title_bot: "거래 봇",
    order_title_ipo: "IPO",
    order_current_position: "현재 보유 중",
    order_history: "내역 조회",
    assets_center: "자산 센터",

  },
  withdraw: {
    withdraw: "출금",
    withdrawRecord: "출금 기록",
    cryptocurrency: "암호화폐",
    bankCard: "은행 카드",
    currency: "화폐 종류",
    network: "네트워크",
    confirm: "확인",
    currencySelection: "화폐 종류 선택",
    networkSelection: "네트워크 선택",
    searchPlaceholder: "검색",
    addPaymentMethod: "수금 방법 추가",
    withdrawable: "출금 가능",
    withdrawalAmount: "출금 금액",
    serviceFee: "수수료",
    receiptAccount: "수금 계좌",
    change: "계좌 변경",
    accountSelection: "암호화폐 계좌 선택",
    bankSelection: "은행 계좌 선택",
  },
  topUpCrypto: {
    recharge: "충전",
    rechargeRecord: "충전 기록",
    cryptocurrency: "암호화폐",
    bankCard: "은행 카드",
    currency: "화폐 종류",
    network: "네트워크",
    rechargeAmount: "충전 금액",
    inputPlaceholder: "입력하세요",
    confirm: "충전",
    currencySelection: "화폐 종류 선택",
    searchPlaceholder: "검색",
    enterCurrency: "화폐 종류 입력",
    networkSelection: "네트워크 선택",
    no_amount_msg: "금액을 입력하세요",
    getting_rate_msg: "환율을 가져오는 중",
    no_enough_balance: "잔액 부족",
    no_account_msg: "수금 계좌를 추가하세요",
    success_msg: "작업 성공",
    no_auth_title: "신원 인증",
    no_auth_con: "신원 인증이 완료되지 않았습니다. 인증하시겠습니까?",
    no_google_msg: "구글 인증기",
    no_google_con: "구글 인증기를 아직 연결하지 않았습니다. 연결하시겠습니까?",
  },
  withdrawInfo: {
    title: "출금 상세",
    successful: "출금 성공",
    failed: "출금 실패",
    failurePrompt: "다시 출금하시거나 고객센터에 문의하세요",
    processing: "출금 처리 중",
    processingTip: "출금 결과를 기다려 주세요",
    info_recharge_success_con1: "출금하신",
    info_recharge_success_con2: "금액이 입금되었습니다",
    withdrawalAmount: "출금 금액",
    receivingAccount: "수금 계좌",
    withdrawalCurrency: "출금 화폐 종류",
    withdrawalNetwork: "출금 네트워크",
    orderNumber: "주문 번호",
    withdrawalTime: "출금 시간",
  },
  recharging: {
    recharge: "충전",
    countdown: "충전 카운트다운",
    QRcodeExpired: "QR 코드가 만료되었습니다",
    walletAddress: "수금자 지갑 주소",
    copy: "복사",
    tip1: "알림: 마감 시간 내에 충전을 완료해 주세요",
    tip2: "주문 만료 시 무효 처리됩니다",
    success: "성공",
    fail: "실패",
    finish: "완료",
    info_title: "충전 상세",
    info_recharge_success: "충전 성공",
    info_recharge_success_con1: "충전하신",
    info_recharge_success_con2: "금액이 입금되었습니다",
    info_recharge_failure: "충전 실패",
    info_recharge_failure_con: "다시 충전하시거나 고객센터에 문의하세요",
    info_recharge_pending: "충전 처리 중",
    info_recharge_pending_con: "충전 결과를 기다려 주세요",
    info_recharge_balance: "충전 금액",
    info_recharge_crpyto: "충전 화폐 종류",
    info_recharge_network: "충전 네트워크",
    info_recharge_address: "충전 주소",
    info_recharge_order: "주문 번호",
    info_recharge_date: "충전 시간",
    copied: "복사 완료",
  },
  transfer: {
    transferRecord: "이체 기록",
    page_title: "이체",
    out: "출금",
    out_sim: "출금",
    out_amount: "금액을 입력하세요",
    in: "입금",
    in_sim: "입금",
    in_amount: "금액을 입력하세요",
    btn: "이체",
    confirm: "확인",
    confirm_con: "입금 계좌",
    no_amount: "금액을 입력하세요",
    no_enough_balance: "잔액 부족",
    account_same: "동일 계좌 간에는 이체할 수 없습니다",
    success: "이체 성공",
    transfer_map_money: "현금 계좌",
    transfer_map_stock: "주식 계좌",
    transfer_map_futures: "계약 계좌",
    transfer_map_forex: "외환 계좌",
    transfer_map_trade: "원자재 계좌",
  },
  recordList: {
    financialRecords: "자금 기록",
    rechargeRecord: "충전 기록",
    withdrawalRecord: "출금 기록",
    transfer: "이체 기록",
  },
  accountMap: {
    cashAccount: "현금 계좌",
    stockAccount: "주식 계좌",
    contractAccount: "계약 계좌",
    foreignExchangeAccount: "외환 계좌",
  },
  topUpStatusMap: {
    review: "충전 검토 중",
    success: "충전 성공",
    failure: "충전 실패",
    unknown: "충전 처리 중",
  },
  withdrawStatusMap: {
    review: "출금 처리 중",
    success: "출금 성공",
    failure: "출금 실패",
    unknown: "출금 처리 중",
  },
  trade: {
    header_stock: "주식",
    header_contract: "계약",
    header_aibot: "거래 로봇",
    header_ipo: "IPO",
    header_forex: "외환",
    header_block: "원자재",
    header_block_long: "원자재",
    stock_open: "매수",
    stock_position: "포지션",
    stock_search: "조회",
    stock_open_long: "상승 매수",
    stock_open_short: "하락 매도",
    stock_open_long_tab: "상승 매수",
    stock_open_short_tab: "하락 매도",
    stock_market_price: "시세",
    stock_limit_price: "한정 가격",
    stock_take_stop: "익절/손절",

    left_search: "검색",
    left_mine: "내 선택",
    left_stock: "주식",
    left_contract: "계약",
    left_bot: "거래 로봇",
    left_forex: "외환",
    left_all: "전체",

    stock_opening_take: "익절",
    stock_opening_stop: "손절",
    stock_opening_price: "가격",
    stock_opening_price_market: "시장가",
    stock_opening_price_limit: "한정가",
    stock_opening_price_latest: "최신 가격 거래",
    stock_opening_price_title: "가격",
    stock_opening_price_tip: "가격이 충족되어야 거래가 체결됩니다",
    stock_opening_price_label: "시장가",
    stock_opening_stock: "주식",
    contract_opening_contract: "계약",
    stock_opening_amount_mode: "보증금 모드",
    stock_opening_amount_limit_mode: "한정가 모드",
    stock_opening_show_jump_type: "이체/환전/충전",
    stock_opening_amount_title: "수량(주)",
    stock_opening_no_balance: "계좌 잔액 부족",
    stock_opening_enough_balance: "잔액",
    stock_opening_token_login: "로그인",
    stock_opening_token_register: "가입",
    stock_opening_confirm_title: "매수 확인",
    stock_opening_amount: "매수 수량",
    contract_opening_amount: "계약 수량",
    stock_opening_no: "없음",
    stock_opening_pay: "결제",
    stock_opening_upfront: "보증금",
    stock_opening_fee: "수수료",
    stock_opening_trade_pw: "거래 비밀번호",
    stock_opening_trade_pw_placeholder: "거래 비밀번호를 입력하세요",
    stock_opening_confirm: "확인",
    stock_opening_search: "검색",
    stock_opening_jump_mode1: "이체",
    stock_opening_jump_mode2: "이체",
    stock_opening_jump_mode3: "이체",
    stock_opening_position_mode_cross: "전체 포지션",
    stock_opening_position_mode_isolated: "격리 포지션",
    stock_account_balance: "주식 계좌 잔액",
    stock_account_notification: "충전 또는 이체가 필요합니다",
    stock_opening_btn_transfer: "이체하기",
    stock_opening_btn_recharge: "충전하기",
    stock_opening_btn_trade: "거래하기",
    stock_opening_stop_price: "가격",
    stock_opening_stop_amount: "금액",
    stock_opening_stop_ratio: "비율",
    stock_opening_err_stock: "주식을 선택하세요",
    stock_opening_err_min_balance: "최소 거래량",
    stock_opening_err_price: "가격을 입력하세요",
    stock_opening_err_take_price: "익절 가격을 입력하세요",
    stock_opening_err_stop_price: "손절 가격을 입력하세요",
    stock_opening_err_limit: "한정가를 입력하세요",
    stock_opening_success: "매수 성공",
    stock_opening_lever: "레버리지",
    stock_opening_closed: "장 종료, 거래 불가",

    stock_position_stock: "주식/상태",
    stock_position_open: "매수/판매 가능",
    stock_position_cost: "현재 가격/원가",
    stock_position_profit: "손익/비율",
    stock_position_close: "매도",
    stock_position_close_order: "매도",
    stock_position_amount: "수량",
    stock_position_ongoing_amount: "보유 수량",
    stock_position_all: "전체",
    stock_position_btn: "확인",
    stock_position_update: "주문 갱신",
    stock_position_add_deposit: "보증금 추가",
    stock_position_no_close_amount: "매도 수량을 입력하세요",
    stock_position_success: "작업 성공",
    stock_position_no_deposit: "보증금을 입력하세요",
    stock_position_cancel_title: "주문 취소",
    stock_position_cancel_con: "주문을 취소하시겠습니까?",
    stock_position_cancel_btn: "취소",
    stock_position_confirm_btn: "확인",
    stock_position_status_none: "매수 중",
    stock_position_status_lock: "잠금",
    stock_position_status_open: "보유 중",
    stock_position_status_done: "매도 완료",
    stock_position_status_fail: "실패",
    stock_position_status_cancel: "취소됨",
    stock_position_offset_long: "상승 매수",
    stock_position_offset_short: "하락 매도",
    stock_position_stop_price: "가격",
    stock_position_stop_amount: "금액",
    stock_position_stop_ratio: "비율",
    stock_position_unlogin_title: "아직 로그인하지 않았습니까?",
    stock_position_unlogin_con: "지금 로그인",

    order_info_title_stock: "주식 주문",
    order_info_title_contract: "계약 주문",
    order_info_available_stock: "판매 가능한 주식",
    order_info_available_contract: "판매 가능한 계약 수",
    order_info_profit: "손익",
    order_info_ratio: "손익 비율",
    order_info_update: "갱신",
    order_info_cancel: "주문 취소",
    order_info_open_qty_contract: "매수 계약 수",
    order_info_open_qty_other: "매수 수량",
    order_info_stop_profit_price: "익절 가격",
    order_info_stop_profit_amount: "익절 금액",
    order_info_stop_profit_ratio: "익절 비율",
    order_info_stop_loss_price: "손절 가격",
    order_info_stop_loss_amount: "손절 금액",
    order_info_stop_loss_ratio: "손절 비율",
    order_info_value: "주문 가치",
    order_info_copy: "복사됨",

    contract_position_no_close_amount: "매도 계약 수를 입력하세요",
    contract_position_ongoing_amount: "보유 계약 수",
    contract_position_cost: "현재 가격/매수 가격",
    contract_opening_amount_title: "계약 수량",
    contract_opening_order_value: "주문 금액",
    contract_opening_err_contract: "계약을 선택하세요",
    contract_opening_err_amount: "수량을 입력하세요",
    contract_create_guest_btn: "게스트 계정으로 가입",
    contract_lots_amount: "수량(계약)",
    contract_one_lot: "계약",

    ai_opening_order: "주문",
    ai_opening_trade: "거래",
    ai_opening_long: "상승",
    ai_opening_short: "하락",
    ai_opening_product_type: "거래 품종",
    ai_opening_time_zone: "시간대",
    ai_opening_network_amount: "그리드 수",
    ai_opening_bigest_network: "최대 그리드",
    ai_opening_every_profit: "각 그리드 이익",
    ai_opening_invest_amount: "투자 금액",
    ai_opening_balance: "잔액",
    ai_opening_login: "로그인",
    ai_opening_register: "가입",
    ai_opening_confirm_order: "주문 확인",
    ai_opening_predict_profit: "예상 손익 금액",
    ai_opening_confirm_btn: "확인",
    ai_opening_ai_quantifi_list: "AI 퀀텀 리스트",
    ai_opening_cash_wallet: "현금 계좌",
    ai_opening_no_net: "그리드 수를 입력하세요",
    ai_opening_no_product: "품종을 선택하세요",
    ai_opening_no_invest_amount: "투자 금액을 입력하세요",
    ai_opening_min_invest_amount: "최소 투자 금액",
    ai_opening_trade_password: "거래 비밀번호를 입력하세요",
    ai_opening_success: "매수 성공",
    ai_opening_pop_title: "계좌 잔액",
    ai_opening_pop_recharge: "충전하기",
    ai_opening_pop_transfer: "이체하기",
    ai_opening_perform_time: "실행 시간",
    ai_opening_historical_profit_rate: "역사적 수익률",
    ai_opening_24_profit_rate: "24시간 수익률",
    ai_opening_profit_margin: "수익률",
    ai_opening_profit_ratio: "손익 비율",

    ai_position_title: "주문 상세",
    ai_position_profit: "이익",
    ai_position_timer: "카운트다운",
    ai_position_end_trade: "거래 종료",
    ai_position_order_id: "주문 ID",

    ipo_title: "주문",
    ipo_title_all: "전체",
    ipo_title_pre: "사전 판매 중",
    ipo_title_going: "구매 중",
    ipo_title_finish: "종료됨",
    ipo_title_market: "상장됨",
    ipo_detail_price: "구매 가격",
    ipo_detail_time: "상장 시간",
    ipo_detail_date: "구매 일자",
    ipo_detail_lever: "구매 레버리지",
    ipo_detail_listing_price: "상장 가격",
    ipo_detail: "IPO 상세",
    ipo_opening_btn: "구매",
    ipo_detail_item1: "주식 코드",
    ipo_detail_item2: "구매 가격",
    ipo_detail_item3: "구매 시작일",
    ipo_detail_item4: "구매 종료일",
    ipo_detail_item5: "상장 일자",
    ipo_detail_item6: "상장 가격",
    ipo_detail_item7: "최소 구매 수량",
    ipo_detail_item8: "VIP 구매",
    ipo_detail_item9: "수수료",
    ipo_detail_item10: "구매 수량",
    ipo_detail_item11: "소속 시장",
    ipo_detail_item12: "주문 금액",
    ipo_detail_item13: "주문 수량",
    ipo_detail_item14: "동결 금액",
    ipo_detail_btn: "구매하기",
    ipo_account_balance: "IPO 계좌 잔액",

    ipo_lottery_title1: "전체",
    ipo_lottery_title2: "당첨 대기",
    ipo_lottery_title3: "당첨됨",
    ipo_lottery_title4: "당첨 안됨",
    ipo_lottery_title5: "동결",
    ipo_lottery_title6: "당첨",
    ipo_lottery_amount: "당첨 수량",
    ipo_lottery_detail: "당첨 상세",
    ipo_leveraged_trading: "레버리지 거래",
    ipo_sub_ordinary: "일반",
    ipo_sub_leveraged: "레버리지",
    ipo_sub_buy_code: "구매 코드",
    ipo_sub_buy_no_amount: "구매 수량을 입력하세요",
    ipo_sub_buy_no_code: "구매 코드를 입력하세요",
    ipo_success_title: "구매 성공",
    ipo_success_con: "축하합니다, 구매 성공! 당첨 정보를 기다려주세요.",
    ipo_success_btn1: "계속 구매",
    ipo_success_btn2: "주문 상세",

    ipo_detail_title: "주문 상세",
    ipo_detail_loading: "로딩 중",
    ipo_detail_status_success: "축하합니다, 당첨되었습니다.",
    ipo_detail_status_wait: "구매 완료, 당첨 대기 중",
    ipo_detail_status_failure: "아쉽게도, 당첨되지 않았습니다.",
    ipo_detail_order_no: "주문 번호",
    ipo_detail_win_num: "당첨 수량",
    ipo_detail_buy_num: "구매 수량",
    ipo_detail_block_num: "동결 금액",
    ipo_detail_buy_value: "구매 금액",
    ipo_detail_fee: "수수료",
    ipo_detail_leverage: "구매 레버리지",
    ipo_detail_market_date: "상장 일자",
    ipo_detail_market_price: "상장 가격",
    ipo_detail_buy_price: "구매 가격",
    ipo_detail_buy_date: "구매 일자",
    ipo_detail_order_date: "주문 일자",

    forex_opening_title: "외환",
    forex_position_title: "외환/상태",
    trade_order_history: "주문 기록",

    left_search_result: "검색 결과",
    spot_trade_available: "판매 가능",
    trade_orders_title: "거래 주문",
    trade_orders_current: "현재 주문",
    trade_orders_status: "상태",
    trade_deal_price: "체결가격",
    trade_search_item: "종목명/코드를 입력하세요",
    spot_trade_market_price: "현재 시장 최적 가격으로 주문",
    spot_time: "시간",
  },
  inviteFriends: {
    invite: "친구 초대",
    reward: "내 보상",
    banner_title: "친구 초대로 받을 수 있는 보상",
    banner_desc: "친구를 초대하여 함께 돈을 벌어보세요",
    qrcode_title: "초대 QR 코드",
    save_img: "이미지 저장",
    img_name: "내 QR 코드",
    invite_code: "초대 코드",
    copy: "복사",
    copy_success: "복사 성공",
    url_title: "초대 링크",
    copy_url: "링크 복사",
    performance_title: "추천 성과",
    details: "추천 세부 내역",
    user: "사용자",
    performance: "성과",
  },
  market: {
    market_header_optional: "자유 선택",
    market_header_buy: "코인 구매",
    market_header_stock: "주식",
    market_header_contract: "계약",
    market_header_ai: "거래 봇",
    market_header_forex: "외환",

    market_optional_add: "자유 선택 추가",
    market_optional_no_optional: "아직 자유 선택을 추가하지 않았습니다",
    market_optional_add_all: "모두 자유 선택 추가",
    market_optional_recommend_stock: "추천 주식",
    market_optional_recommend_crypto: "추천 암호화폐",
    market_optional_add_success: "추가 성공",
    market_optioanl_del_success: "삭제 성공",

    market_optional_crypto_price: "최신 가격",
    market_optional_short: "상승/하락",
    market_optioanl_ratio: "상승/하락 비율",
    market_optional_stock: "주식",
    market_optional_contract: "암호화폐",
    market_optional_forex: "외환",
    market_optional_blocktrade: "대형 상품",

    market_marketinfo_data: "데이터",
    market_marketinfo_trade: "거래",
    market_marketinfo_long: "매수",
    market_marketinfo_short: "매도",
    market_marketinfo_open: "오늘 개시",
    market_marketinfo_high: "최고",
    market_marketinfo_amount: "거래량",
    market_marketinfo_close: "어제 종가",
    market_marketinfo_low: "최저",
    market_marketinfo_value: "거래 금액",

    market_buy_title1: "빠른 거래 구역",
    market_buy_title2: "자유 선택 구역",
    market_buy_title3: "주문",
    market_buy_fast_buy: "구매",
    market_buy_fast_sell: "판매",
    market_buy_fast_buy_btn: "구매",
    market_buy_fast_sell_btn: "판매",
    market_buy_fast_receive: "수령",
    market_buy_fast_receive_sim: "수령",
    market_buy_fast_pay: "결제",
    market_buy_fast_estprice: "예상 가격",
    market_buy_fast_search_title: "코인 선택",
    market_buy_fast_search_input: "코인 입력",
    market_buy_fast_no_amount: "금액을 입력하세요",
    market_buy_fast_noti_title: "알림",
    market_buy_fast_noti_con:
      "지갑 잔액이 부족합니다. 충전 또는 계좌 이체를 해주세요",
    market_buy_fast_noti_cancel: "충전하러 가기",
    market_buy_fast_noti_confirm: "이체하러 가기",
    market_buy_fast_success: "주문 성공",
    market_buy_fast_account_title: "계좌 선택",
    market_buy_fast_account_crypto: "암호화폐",
    market_buy_fast_account_bank: "은행 계좌",
    market_buy_fast_account_add: "수령 계좌 추가",
    market_buy_optional_deal: "거래량",
    market_buy_optional_rate: "거래율",
    market_buy_optional_duaration: "분",
    market_buy_optional_order_limit: "주문 한도",
    market_buy_optional_buy: "구매",
    market_buy_optional_sell: "판매",
    market_buy_optional_estreceive: "예상 수령액",
    market_buy_optional_limit_val: "한도",
    market_buy_optional_confirm: "확인",

    market_buy_list_buy: "구매",
    market_buy_list_sell: "판매",
    market_buy_list_price: "가격",
    market_buy_list_amount: "수량",
    market_buy_list_wait_pay: "결제 대기 중",
    market_buy_list_wait_confirm: "확인 대기 중",
    market_buy_list_wait_pay1: "대기 결제",
    market_buy_list_wait_confirm1: "대기 확인",
    market_buy_list_complete: "거래 완료",
    market_buy_list_cancel: "거래 취소",
    market_buy_list_contact: "판매자와 연락하기",
    market_buy_list_wait_buyer_confirm: "구매자 결제 대기 중",
    market_buy_list_wait_buyer_con:
      "전체 금액에 맞춰 판매자에게 제공된 은행 계좌로 이체해주세요",
    market_buy_list_wait_con: "결제 완료, 판매자 확인 대기 중",
    market_buy_list_wait_result: "판매자가 결제 완료, 자금 입금 여부 확인 중",
    market_buy_list_wait_buyer_bank: "판매자에게 은행 계좌 제공 대기 중",
    market_buy_list_wait_bank_no: "계좌번호",
    market_buy_list_wait_account: "계좌",
    market_buy_list_wait_total: "총액",
    market_buy_list_wait_price: "가격",
    market_buy_list_wait_amount: "수량",
    market_buy_list_cancel_order: "주문 취소",
    market_buy_list_paid: "결제 완료",
    market_buy_list_received: "수령 완료",
    market_buy_list_trade_sccess: "거래 완료",
    market_buy_list_paid_success: "결제 성공",
    market_buy_list_pass_success: "승인 성공",
    market_buy_list_cancel_success: "취소 성공",
    market_buy_list_pre_pay: "예상 결제",
    market_buy_list_firt_select: "먼저 수령 계좌를 추가하세요",
    market_buy_chat_con1: "주문이 성공적으로 완료되었습니다",
    market_buy_chat_con2: "판매자의 결제를 기다려주세요",

    market_stock_country_us: "미국",
    market_stock_country_japan: "일본",
    market_stock_country_india: "인도",
    market_stock_country_korea: "한국",
    market_stock_country_germany: "독일",
    market_stock_country_uk: "영국",
    market_stock_country_singapore: "싱가포르",
    market_stock_country_hongkong: "홍콩",
    market_stock_country_malaysia: "말레이시아",
    market_stock_country_us_long: "미국",
    market_stock_country_japan_long: "일본",
    market_stock_country_india_long: "인도",
    market_stock_country_korea_long: "한국",
    market_stock_country_germany_long: "독일",
    market_stock_country_uk_long: "영국",
    market_stock_country_singapore_long: "싱가포르",
    market_stock_country_hongkong_long: "홍콩",
    market_stock_country_malaysia_long: "말레이시아",
    market_stock_updatetime: "업데이트 시간",
    market_stock_description_title: "상승/하락 분포",
    market_stock_description_des1: "상승",
    market_stock_description_des2: "하락",
    market_stock_description_long_end: "상한가",
    market_stock_description_center: "보합",
    market_stock_description_short_end: "하한가",
    market_stock_chase_movement: "상한가 추격",
    market_stock_chase_earning_effect: "수익 효과",
    market_stock_chase_strong: "강",
    market_stock_chase_movement_percentage: "상한가/하한가 비교",
    market_stock_chase_todays_effect: "오늘의 상한가 성과",
    market_stock_chase_long_sort: "상승 순위",
    market_stock_chase_short_sort: "하락 순위",
    market_stock_hot: "핫 주식",
    market_ai_title1: "기본",
    market_ai_title2: "역사적 높은 수익률",
    market_ai_title3: "24시간 높은 수익률",
    market_ai_title4: "높은 레버리지",
    market_search_title: "검색",
    market_search_history: "검색 기록",
    market_search_recommend: "인기 검색",
    market_search_des: "2만명 이상 검색",

    market_buy_confirm_coin: "주문 확인",
    market_buy_will_pay: "지불할 금액",
    market_buy_will_sell: "판매할 금액",
    market_buy_will_receive: "수령할 금액",

    market_faster_available: "사용 가능 잔액",
    market_already_done: "이미 완료",
    market_already_cancel: "이미 취소",

    market_order_details_wait: "대기 중",
    market_order_details_for_buyer: "구매자 결제",
    market_order_details_for_seller: "판매자 확인",
    market_order_details_con1: "전체 금액에 맞춰",
    market_order_details_con2: "판매자가 제공한 은행 계좌로 이체해 주세요",
    market_item_detail: "시장",
    market_item_order: "주문서",
    market_item_news: "최신 체결",
    market_input_crypto_set: "거래 쌍 입력",
    market_login_first: "먼저 로그인 후 즐겨찾기를 확인하세요",

  },
  finance: {
    portfolio: "재무관리",
    portfolio_menu: "투자 포트폴리오",
    portfolio_title: "스테이킹 및 채굴",
    portfolio_order: "주문",
    portfolio_revenue: "총 수익",
    portfolio_investment_amt: "투자금액",
    portfolio_yield: "수익률",
    portfolio_duration: "기간",
    portfolio_participate: "참여하기",
    portfolio_hot: "핫",
    portfolio_day: "일",
    portfolio_day_multi: "일(s)",
    portfolio_mining_title: "스테이킹 및 채굴",
    portfolio_mining_subTitle1: "구독 조합",
    portfolio_mining_subTitle2: "구독 금액",
    portfolio_mining_operation: "운영 시간",
    portfolio_mining_revenue: "수익",
    portfolio_mining_investment: "투자금액",
    portfolio_mining_fee: "수수료",
    portfolio_mining_header: "구독 금액",
    portfolio_mining_balance: "계좌 잔고",
    portfolio_mining_placeholder: "투자 금액을 입력하세요",
    portfolio_mining_btn: "구독하기",
    portfolio_mining_title3: "운영 방법?",
    portfolio_mining_guide:
      "Coinbase, Huobi, Binance, KuCoin, YFX와 같은 전 세계적인 거래소를 통해 다양한 암호화폐의 트렌드를 판단하는 알고리즘을 사용하여, 실시간으로 시장 상황을 모니터링하고, 가격 범위 내에서 고빈도 거래를 통해 차익 거래를 진행하여 최대의 수익을 얻습니다.",
    portfolio_mining_noti: "알림",
    portfolio_mining_noti_duration: "운영 시간",
    portfolio_mining_noti_daily: "일일 수익률",
    portfolio_mining_noti_est: "예상 수익",
    portfolio_mining_noti_investment: "투자 금액",
    portfolio_mining_noti_fee: "수수료 금액",
    portfolio_order_title: "투자 주문",
    portfolio_order_tab1: "포지션",
    portfolio_order_tab2: "상환 완료",
    portfolio_order_finish_time: "만료 일자",
    portfolio_repay_date: "상환 시간",

    defi_borrow: "디파이 대출",

    defi_coll_borrow: "담보 대출",
    defi_borrow_order: "대출 주문",
    defi_verif_qty: "확인 가능 수량",
    defi_verifiable_qty: "확인 가능한 금액",
    defi_avail_qty: "사용 가능한 수량",
    defi_borrow_period: "대출 기간",
    defi_daily_interest: "일일 이자율",
    defi_borrow_now: "코인 대출하기",
    defi_total_interest: "총 이자",
    defi_service_charge: "총 서비스 수수료",
    defi_repayment_due: "상환 예정일",
    defi_borrow_agreement1: "저는 읽고 동의합니다",
    defi_borrow_agreement2: "대출 서비스 약관",

    defi_borrow_confirm: "주문 확인",
    defi_borrow_stake_amount: "스테이킹 금액",
    defi_borrow_borrow_amount: "대출 금액",

    defi_borrow_already: "대출 완료",
    defi_borrow_remain: "남은 대출 금액",
    defi_borrow_on: "대출 중",
    defi_borrow_repaid: "상환 완료",
    defi_borrow_repay: "상환하기",
    defi_borrow_go_repay: "상환 진행",

    defi_borrow_total_due: "총 상환 금액",

    defi_borrow_est_due: "예상 상환 금액",
    defi_borrowed_day: "대출 일수",
    defi_borrow_cal_bill: "누적 이자",
    defi_borrow_return_confirm: "상환 확인",
    borrow_crypto: "대출",
    staking_crypto: "스테이킹",
  },

  copy: {
    title: "주문 따라하기",
    copy_option: "옵션",
    copy_trade: "복사",
    total_revenue: "총 수익",
    level: "LV.{level}",

    copy_ground: "팔로우 플라자",

    copy_tab_tab1: "복사",
    copy_tab_tab2: "주문",
    copy_portfolio: "포트폴리오",
    copy_profit_rate: "승률",
    copy_belong_profit: "수익",
    copy_belong_title: "주문 실행 성과",
    copy_belong_tab1: "성과",
    copy_belong_profit_rate: "수익률",
    copy_belong_profit_amount: "수익 금액",
    copy_belong_total_amount: "주문 규모",
    copy_belong_days: "주문 일수",
    copy_belong_profit_days: "수익이 난 일수",
    copy_belong_pl_rate: "손익 비율",
    copy_belong_loss_days: "손실이 난 일수",
    copy_belong_sharing_ratio: "수익 분배 비율",
    copy_belong_tab2: "주문",
    copy_belong_subtitle1: "심볼/상태",
    copy_belong_subtitle2: "포지션/시간",
    copy_belong_subtitle3: "투자 금액",
    copy_belong_subtitle4: "예상 수익",
    copy_belong_open1: "롱",
    copy_belong_open2: "숏",
    copy_belong_tab3: "팔로워",
    copy_belong_subtitle5: "사용자 이름",
    copy_belong_subtitle6: "주문 규모",
    copy_belong_subtitle7: "수익",
    copy_confirm_range: "주문 한도",
    copy_order_total_profit: "팔로우한 주문의 총 수익",
    copy_order_total_amount: "주문 총 금액",
    copy_order_daily_profit: "오늘의 수익",
    copy_order_cancel: "주문 취소",
    copy_order_follow: "주문 따라하기",
    copy_order_follow_confirm_title: "주문 따라하기",
    copy_order_follow_confirm_rage: "주문 한도",
    copy_order_cancel_title: "주문 취소",
    copy_order_cancel_con: "팔로우한 주문을 취소하시겠습니까?",
    copy_order_cancel_cancel: "취소",
    copy_order_cancel_confirm: "확인",
    copy_order_detail_title: "세부 사항",
    copy_order_detail_on: "복사 중",
    copy_order_detail_duration: "팔로우 시간",
    copy_order_detail_cancel: "주문 취소",
    copy_order_detail_confirm: "주문 따라하기",
    copy_order_detail_tab1: "현재 주문",
    copy_order_detail_tab2: "과거 주문",

    copy_apply_now: "지금 신청",
    copy_apply_con:
      "복사 거래자가 되어 최대 30% 복사 거래 수익 분배 + 10% 거래 수수료 리베이트를 받으세요",
    copy_trade_con:
      "전 세계 최고의 암호화폐 트레이더들이 당신을 이끌어 한 번의 클릭으로 거래를 복사하고 수익을 얻을 수 있습니다",
    copy_order_status: "복사 거래 상태",
    copy_order_time1: "최근 1년",
    copy_leader_overview: "복사 거래자 개요",
    copy_leader_order_amount: "트레이더의 복사 거래 자산",
    copy_leader_order_size: "복사 거래 규모",
    copy_leader_followers_profit: "현재 팔로워 수익",
    copy_leader_followers_num: "팔로워 수",
    copy_leader_profit_amount: "총 수익",
    copy_follower_amount: "총 팔로워 수",

    copy_profit_divide_ratio: "수익 배분 비율",
    copy_order_name: "이름",
    copy_order_direction: "포지션 방향",
    copy_order_price: "구매/현재 가격",
    copy_paid_date: "결제 시간",
    copy_start_date: "시작 시간",
    copy_finish_date: "종료 시간",
  },
  notifi: {
    notifi_center: "알림센터",
    notifi_pub: "공지사항",
    notifi_marke: "마켓이벤트",
    notifi_detail: "상세 보기",
    notifi_join: "이벤트참여",
    notifi_joined: "이벤트참여완료",
    btn_see_all: "모두보기",
    btn_cancel: "취소",
  },
};
