export default {
  login: {
    login: "Sing In",
    email: "Email",
    phone: "Phone",
    phone_number: "Phone number",
    password: "Password",
    forget_pw: "Forgot Password?",
    country_number: "Country number",
    pw_placeholder1: "Please input your email",
    pw_placeholder2: "Please input your phone number",
    pw_placeholder3: "Please input your password",
    pw_placeholder4: "Please input the country number",
    no_account_con1: "Has not an account?",
    no_account_con2: "Go to sign up",
    no_account_warning: "Can not find this account",
    login_success: "Signed in successfully",
    login_failed: "Failed to sign in",
    network_error: "Network Error",
  },
  register: {
    security: "Security Verification",
    security_con: "Drag the slider to make the image angle positive",
    security_result_success: "Verification success",
    security_result_failed: "Verification failed",
    security_result_pedding: "Waiting for sliding verification",
    create_user_account: "Create Your account",
    create_user_account: "Create your account",
    create_guest_account: "Create a guest account",
    has_account: "Has an account？",
    go_login: "Go to login",
    email: "Email",
    phone: "Phone",
    phone_number: "Phone number",
    login_password: "Login password",
    trade_password: "Trade password",
    forget_pw: "Forget password?",
    country_number: "Country number",
    pw_placeholder1: "Please input your email",
    pw_placeholder2: "Please input your phone number",
    pw_placeholder3: "At least 8 letters for password",
    pw_placeholder4: "Please input the country number",
    pw_placeholder5: "Please input the trade password",
    pw_placeholder6: "Please input the invite code",
    invite_code: "Invite code",
    agree_con1: "I agree with",
    agree_con2: "security policy",
    agree_con3: "and",
    agree_con4: "user rules",
    register_success: "Signed up successfully",
    register_failed: "Failed to sign up",
    network_error: "Network Error",
    next: "Go on",
    code_email: "Email ",
    code_phone: "Phone ",
    code_verify: "Verification",
    code_con1: "Already sent verification code to your ",
    code_con2: "Input 6 letter code",
    code_jump: "Jump verify",
    code_again: 'Send again',

  },
  password_level: {
    weak: "Weak",
    normal: "Normal",
    strong: "Strong"
  },
  code_input: {
    btn_text1: "Next",
    btn_text2: "Bound",
  },
  user_page: {
    login_out: "Sign In / Sign Out",
    recommended_user: "Recommended User",
    social_user: "Social User",
    recommend_bonus: "Recommend Bonus",
    ad_head: "Get invested crypto",
    ad_con1: "Virtual coin",
    ad_con2: "Proceeds on sale",
    receive_payment: "Receiving Account",
    verify_identity: "Identity verify",
    google_verification: "Google Authenticator",
    already_verified: "Set",
    pending_verified: "Pendding",
    not_verified: "Unset",
    already_set: "Bounded",
    not_set: "Unbounded",
    recommend_friend: "Recommend to friends",
    set_language: "Language",
    security: "Security",
    about: "About",
    logout: "Log out",
    already_set_google: "Bounded GGA",
    not_set_google_yet: "Unbounded GGA",
    message_box_con: "Really want to log out?",
    message_box_confirm: "Cancel",
    message_box_cancel: "Confirm",
  },
  form: {
    all: "All",
  },
  assets: {
    recharge: "Recharge",
    withdraw: "Withdraw",
    transfer: "Transfer",
    financialRecords: "Details",
  },
  topUpCrypto: {
    recharge: "Recharge",
    rechargeRecord: "Recharge record",
    cryptocurrency: "Crypto currency",
    bankCard: "Bank card",
    currency: "Currency",
    network: "Network",
    rechargeAmount: "Recharge amount",
    inputPlaceholder: "Please enter",
    confirm: "Confirm",
    currencySelection: "Currency selection",
    searchPlaceholder: "Enter currency",
    networkSelection: "Network selection",
  },
  withdraw: {
    withdraw: "Withdraw",
    withdrawRecord: "Withdraw record",
    cryptocurrency: "Crypto currency",
    bankCard: "Bank card",
    currency: "Currency",
    network: "Network",
    confirm: "Confirm",
    currencySelection: "Currency selection",
    searchPlaceholder: "Enter currency",
    addPaymentMethod: "Add payment method",
    withdrawable: "Withdrawable",
    withdrawalAmount: "Withdrawal amount",
    serviceFee: "Service fee",
    receiptAccount: "Receipt account",
    change: "Change",
    accountSelection: "Account selection",
  },
  recharging: {
    recharge: "Recharge",
    countdown: "Countdown",
    QRcodeExpired: "QR code expired",
    walletAddress: "Payee's wallet address",
    copy: "Copy",
    tip1: "Tip: Please complete the recharge within the deadline",
    tip2: "Order expiration and cancellation",
    success: "Success",
    fail: "Fail",
    finish: "Finish",
  },
  withdrawInfo: {
    title: "Withdrawal details",
    successful: "Successful",
    failed: "Failed",
    failurePrompt: "Please withdraw again or contact customer service",
    processing: "Processing",
    processingTip: "Please wait for the withdrawal result",
    withdrawalAmount: "Amount",
    receivingAccount: "Account",
    withdrawalCurrency: "Currency",
    withdrawalNetwork: "Network",
    orderNumber: "Order Number",
    withdrawalTime: "Time",
  },
  transfer: {
    transferRecord: "transfer record",
  },
  recordList: {
    financialRecords: "Financial records",
    rechargeRecord: "Recharge",
    withdrawalRecord: "Withdrawal",
    transfer: "Transfer",
  },
  accountMap: {
    cashAccount: "Cash account",
    stockAccount: "Stock account",
    contractAccount: "Contract account",
    foreignExchangeAccount: "Foreign exchange account",
  },
  topUpStatusMap: {
    review: "Under review",
    success: "Successful",
    fail: "Failed",
    unknown: "Unknown",
  },
  withdrawStatusMap: {
    review: "Under review",
    success: "Successful",
    fail: "Failed",
    unknown: "Unknown",
  },
};
