
export default {
    common:{
        stock:"股票",
        crypto:"合约",
        AI:"交易机器人",
        IPO:"IPO",
        closed:"已收盘"
    },
    home:{
        login:'登录',
        loginDesc:"登录才能查看资产",
        totalAssets:"总资产",
        fastTrading:"快速交易",
        recharge:"充值",
        today:"今日",
        index:"指数",
        hotSale:"热卖",
        marketRecommend:"市场推荐",
        selfSelectedRecommend:"自选推荐"
    },
    market:{
        stock:{
            updateTime:"更新时间",
            riseAndFall:"涨跌分布",
            up:'上涨',
            down:'下跌',
            limitUpPursuit:"涨停追击",
            profitMakingEffect:"赚钱效应",
            strong:"强",
            weak:'弱',
            contrast:"涨跌停对比",
            performance:"做涨停今表现",
            hot:"热门股",
            upList:"涨幅榜",
            downList:"跌幅榜"
        }
    },
    form:{
        all:"全部"
    },
    assets:{
        recharge:"充值",
        withdraw:"提现",
        transfer:"划转",
        financialRecords:"资金记录"
    },
    topUpCrypto:{
        recharge:"充值",
        rechargeRecord:"充值记录",
        cryptocurrency:"加密货币",
        bankCard:"银行卡",
        currency:"币种",
        network:"网络",
        rechargeAmount:"充值金额",
        inputPlaceholder:"请输入",
        confirm:"确定",
        currencySelection:"币种选择",
        searchPlaceholder:"搜索",
        enterCurrency:"输入币种",
        networkSelection:"网络选择"
    },
    withdraw:{
        withdraw:"提现",
        withdrawRecord:"提现记录",
        cryptocurrency:"加密货币",
        bankCard:"银行卡",
        currency:"币种",
        network:"网络",
        confirm:"确定",
        currencySelection:"币种选择",
        networkSelection: "网络选择",
        searchPlaceholder:"搜索",
        addPaymentMethod:"添加收款方式",
        withdrawable:"可提现",
        withdrawalAmount:"提现金额",
        serviceFee:"手续费",
        receiptAccount:"收款账户",
        change:"更改",
        accountSelection:"加密货币账户选择",
        bankSelection: "银行卡账户选择"
    },
    withdrawInfo:{
        title:'提现详情',
        successful:"提现成功",
        failed:"提现失败",
        failurePrompt:"请重新提现，或联系客服",
        processing:"提现处理中",
        processingTip:"请等待提现结果",
        withdrawalAmount:"提现金额",
        receivingAccount:"收款账户",
        withdrawalCurrency:"提现币种",
        withdrawalNetwork:"提现网络",
        orderNumber:"订单编号",
        withdrawalTime:"提现时间"

    },
    recharging:{
        recharge:"充值",
        countdown:"充值倒计时",
        QRcodeExpired:"二维码已过期",
        walletAddress:"收款人钱包地址",
        copy:"复制",
        tip1:'提示：请在截至时间内完成充值',
        tip2:'订单到期作废',
        success:"成功",
        fail:'失败',
        finish:'完成'

    },
    transfer:{
        transferRecord:"划转记录"
    },
    recordList:{
        financialRecords:"资金记录",
        rechargeRecord:'充值记录',
        withdrawalRecord:'提现记录',
        transfer:'划转记录'
    },
    accountMap:{
        cashAccount:"现金账户",
        stockAccount:'股票账户',
        contractAccount:'合约账户',
        foreignExchangeAccount:'外汇账户'
        
    },
    topUpStatusMap:{
        review:'充值审核中',
        success:'充值成功',
        failure:'充值失败',
        unknown:'充值处理中'
    },
    withdrawStatusMap:{
        review:'提现处理中',
        success:'提现成功',
        failure:'提现失败',
        unknown:'提现处理中'
    }
}