export default {
  common: {
    stock: "Stocks",
    crypto: "Futures",
    AI: "Bots",
    IPO: "IPO",
    closed: "Closed",
    no_data: "No Data",
    day: "d",
    hour: "h",
    min: "m",
    no_more: "No more",
  },
  login: {
    login: "Log In",
    email: "Email",
    phone: "Phone",
    phone_number: "Phone Number",
    password: "Password",
    forget_pw: "Forgot Password?",
    country_number: "Country Code",
    pw_placeholder1: "Enter your email",
    pw_placeholder2: "Enter your phone number",
    pw_placeholder3: "Enter your password",
    pw_placeholder4: "Enter country code",
    no_account_con1: "Don't have an account?",
    no_account_con2: "Sign up here",
    no_account_warning: "Account not found",
    login_success: "Successfully signed in",
    login_failed: "Login failed",
    network_error: "Network error",
  },
  register: {
    security: "Security Check",
    security_con: "Drag to rotate image",
    security_result_success: "Verification successful",
    security_result_failed: "Verification failed",
    security_result_pending: "Please complete the security check",
    create_user_account: "Create Account",
    create_guest_account: "Create Guest Account",
    has_account: "Have an account?",
    go_login: "Log in",
    email: "Email",
    phone: "Phone",
    phone_number: "Phone Number",
    login_password: "Login Password",
    trade_password: "Transaction Password",
    forget_pw: "Forgot password?",
    country_number: "Country Code",
    pw_placeholder1: "Enter your email",
    pw_placeholder2: "Enter your phone number",
    pw_placeholder3: "At least 8 characters",
    pw_placeholder4: "Enter country code",
    pw_placeholder5: "Enter transaction password",
    pw_placeholder6: "Enter referral code",
    invite_code: "Referral Code",
    agree_con1: "I agree to the",
    agree_con2: "Privacy Policy",
    agree_con3: "and",
    agree_con4: "User Terms",
    register_success: "Registration successful",
    register_failed: "Registration failed",
    network_error: "Network error",
    next: "Next",
    code_email: "Email",
    code_phone: "Phone",
    code_verify: "Verification",
    code_con1: "Verification code sent to your",
    code_con2: "Enter the 6-digit code",
    code_jump: "Skip verification",
    code_again: "Resend code",
    code_jump_title: "Skip verification",
    code_jump_confirm: "Confirm",
    success_sign_up: "Sign-up successful",
    success_btn: "Setup Identity & Google Auth",
    success_finish: "Finish",
    no_email_error: "Enter a valid email address",
    no_phone_error: "Enter your phone number",
    no_login_pw_error: "Enter your password",
    login_pw_length_error: "Password must be at least 8 characters",
    no_trade_pw_error: "Enter your transaction password",
    no_agree_error: "Agree to Privacy Policy & User Terms first",
    network_error: "Network error, try again",
    guest_account: "Guest Account",
    already_get_virtual: "Demo funds credited",
    user_already_exist: "User already exist",
    enter_graphic_number: "Enter numbers in picture",
    not_clear: "Not clear, change to another",
    enter_verify_code: "Enter verify code",
    verify_code_error: "Errors in getting verify code, please do manually",
  },
  password_level: {
    weak: "Weak",
    normal: "Normal",
    strong: "Strong",
  },
  code_input: {
    btn_text1: "Next",
    btn_text2: "Bind",
  },
  user_page: {
    login_out: "Log In / Out",
    recommended_user: "Suggested Users",
    social_user: "Social Users",
    recommend_bonus: "Referral Bonus",
    ad_head: "Invest in Cryptos",
    ad_con1: "Virtual Coins",
    ad_con2: "Earn from sales",
    receive_payment: "Receiving Account",
    verify_identity: "Identity Verification",
    google_verification: "Google Authenticator",
    already_verified: "Verified",
    pending_verified: "Pending",
    not_verified: "Unverified",
    already_set: "Linked",
    not_set: "Unlinked",
    recommend_friend: "Invite Friends",
    set_language: "Language",
    security: "Security",
    about: "About",
    logout: "Log out",
    already_set_google: "Google Auth Linked",
    not_set_google_yet: "Google Auth Unlinked",
    message_box_con: "Are you sure you want to log out?",
    message_box_confirm: "Confirm",
    message_box_cancel: "Cancel",
  },
  kyc: {
    page_title: "Identity Verification",
    first_basic_info: "Basic Info",
    first_upload_card: "Upload ID",
    first_title: "Verify Your Identity",
    first_description:
      "For security, we need to match your details with your government-issued ID.",
    first_legal_name: "Full Name",
    first_card_id: "ID Number",
    first_birthday: "Date of Birth",
    first_birthday_placeholder: "Select your birthdate",
    first_btn: "Next Step",
    first_confirm: "Confirm",
    second_basic_info: "Basic Info",
    second_upload_card: "Upload ID",
    second_title: "Upload Your ID",
    second_description: "Upload your ID for verification",
    second_card_front: "Front of ID",
    second_card_back: "Back of ID",
    second_card_hand: "Hold your ID",
    second_upload_rule: "Photo Guidelines",
    second_upload_description:
      "Ensure the ID is clear, well-lit, and in focus.",
    second_standard_img: "Standard Photo",
    second_failed1: "Incomplete Image",
    second_failed2: "Blurry Image",
    second_failed3: "Too Much Flash",
    second_btn: "Submit",
    final_title: "Identity Verification Submitted",
    final_description:
      "Your ID is being reviewed. We will keep your info confidential.",
    final_ok: "OK",
    status_success: "Verified",
    status_pending: "Under Review",
    status_pending_description:
      "Your verification is under review, please be patient.",
    status_failure: "Verification Failed",
    status_reverify: "Retry Verification",
    status_service: "Contact Support",
    status_card_no: "ID No",
    status_birthday: "Birthday",
  },
  google_auth: {
    page_title: "Google Authenticator",
    from_register_skip: "Skip",
    google_title: "Link Google Authenticator",
    bound_success: "Successfully linked",
    copy_success: "Copied",
    confirm_title: "Skip linking Google Authenticator?",
    google_result_title: "Linked",
    google_result_con:
      "If you have any questions, please contact customer support",
    google_result_btn: "OK",
    google_input_title: "Google Authenticator Code",
    google_input_con: "Enter 6-digit code",
    google_input_btn_cancel: "Cancel",
    google_input_btn_confirm: "Confirm",
  },
  service: {
    page_title: "Customer Service",
    first_message: "Hello, how can I assist you?",
    input_message: "Type your message...",
    message_title: "We're here to help",
  },
  language: {
    page_title: "Language Settings",
  },
  safety: {
    page_title: "Security Settings",
    change_login_pw: "Login Password",
    change_trade_pw: "Transaction Password",
    bind_google_auth: "Google Authenticator",
    google_status_not: "Unlinked",
    google_status_ok: "Linked",
    no_google_dialog_title: "Google Authenticator",
    no_google_dialog_con:
      "You haven't bound Google Authenticator. Set it up now?",
    success_title: "Success",
    success_btn: "Close",
  },
  change_login_pw: {
    page_title: "Change Login Password",
    origin_pw: "Current Password",
    origin_pw_placeholder: "Enter current password",
    new_pw: "New Password",
    new_pw_placeholder: "Enter at least 8 characters",
    confirm_pw: "Confirm New Password",
    confirm_pw_placeholder: "Re-enter new password",
    btn: "Change Password",
    no_match_noti: "Passwords don't match",
  },
  change_trade_pw: {
    page_title: "Change Transaction Password",
    origin_pw: "Current Password",
    origin_pw_placeholder: "Enter current password",
    new_pw: "New Password",
    new_pw_placeholder: "Enter at least 8 characters",
    confirm_pw: "Confirm New Password",
    confirm_pw_placeholder: "Re-enter new password",
    btn: "Change Password",
    no_match_noti: "Passwords don't match",
  },
  account: {
    page_title: "Payment Methods",
    crypto: "Cryptos",
    no_data: "No Wallet Found",
    bank: "Bank Cards",
    no_kyc_title: "Identity Not Verified",
    no_kyc_con: "Verify your identity to add payment methods",
    no_kyc_confirm: "Verify Now",
    no_google_title: "Google Auth Not Linked",
    no_google_con: "Link your Google Auth to add payment methods",
    no_google_confirm: "Link Google Auth",
    add_account_btn: "Add Payment Method",
    delete_dialog_title: "Delete Account",
    delete_dialog_con: "Are you sure you want to remove this account?",
    delete_success: "Account deleted successfully",
    copy_address: "Address copied",
    add_page_title: "Add Payment Method",
    add_tab1: "Cryptos",
    add_tab2: "Bank Cards",
    add_subtitle_type: "Cryptocurrency Type",
    add_subtitle_network: "Network Type",
    add_subtitle_address: "Wallet Address",
    add_address_placeholder: "Enter wallet address",
    add_btn: "Save",
    add_subtitle_user_name: "Account Holder",
    add_subtitle_status: "Verified",
    add_subtitle_bank_name: "Bank Name",
    add_bank_name_placeholder: "Enter bank name",
    add_subtitle_card_number: "Card Number",
    add_bank_address_placeholder: "Enter card number",
  },
  success_toast: {
    message: "Added successfully",
  },
  form: {
    all: "All",
  },
  assets: {
    recharge: "Deposit",
    withdraw: "Withdraw",
    transfer: "Transfer",
    financialRecords: "History",
    header_total: "Overview",
    header_wallet: "Wallets",
    header_order: "Orders",
    info_cash: "Cash",
    info_order: "Order Value",
    over_view_cash: "Cash",
    over_view_stock: "Stock",
    over_view_contract: "Futures",
    over_view_forex: "Forex",
    over_view_trade: "Block Trade",
    wallet_header_cash: "Cash",
    wallet_header_stock: "Stock",
    wallet_header_contract: "Futures",
    wallet_header_forex: "Forex",
    wallet_header_trade: "Block Trade",
    wallet_cash_balance: "Cash Balance",
    wallet_stock_balance: "Stock Balance",
    wallet_contract_balance: "Futures Balance",
    wallet_forex_balance: "Forex Balance",
    wallet_cash_value: "Spot Wallet",
    wallet_stock_value: "Available",
    wallet_contract_value: "Available",
    wallet_forex_value: "Forex Account",
    wallet_order_value: "Position",
    wallet_available: "Available",
    wallet_blocked: "Blocked",
    wallet_available_sim: "Available",
    wallet_blocked_sim: "Blocked",
    wallet_handle_title: "Convert Token",
    coin_list_recharge: "Deposit",
    coin_list_withdraw: "Withdraw",
    coin_list_hide: "Hidden currencies with no balance",
    coin_list_show: "Show currencies with no balance",
    safety_trade_pw: "Trade Password",
    safety_trade_placeholder: "Enter your trade password",
    safety_trade_cancel: "Cancel",
    safety_trade_confirm: "Confirm",
    safety_trade_no_password: "Please enter your password",
    order_title_buy: "Buy Coins",
    order_title_stock: "Stock",
    order_title_contract: "Futures",
    order_title_bot: "Bots",
    order_title_ipo: "IPO",
    order_current_position: "Positions",
    order_history: "History",
  },
  topUpCrypto: {
    recharge: "Deposit Funds",
    rechargeRecord: "History",
    cryptocurrency: "Cryptos",
    bankCard: "Bank Cards",
    currency: "Currency Type",
    network: "Blockchain Network",
    rechargeAmount: "Deposit Amount",
    inputPlaceholder: "Enter amount",
    confirm: "Deposit",
    currencySelection: "Choose Currency",
    searchPlaceholder: "Search for a Currency",
    networkSelection: "Choose Network",
    no_amount_msg: "Please Entera Deposit Amount",
    getting_rate_msg: "Fetching Exchange Rate",
    no_auth_title: "Identity Verification",
    no_auth_con:
      "You have not completed identity verification. Would you like to verify now?",
    no_google_msg: "Google Authenticator",
    no_google_con:
      "You have not linked Google Authenticator. Would you like to link it now?",
  },
  withdraw: {
    withdraw: "Withdraw Funds",
    withdrawRecord: "History",
    cryptocurrency: "Cryptos",
    bankCard: "Bank Cards",
    currency: "Currency Type",
    network: "Blockchain Network",
    confirm: "Withdraw",
    currencySelection: "Choose Currency",
    searchPlaceholder: "Search for Currency",
    addPaymentMethod: "Add Payment Method",
    withdrawable: "Available",
    withdrawalAmount: "Amount",
    serviceFee: "Service Fee",
    receiptAccount: "Receiving Account",
    change: "Edit",
    accountSelection: "Select Account",
    no_amount_msg: "Please enter an amount",
    no_enough_balance: "Insufficient balance",
    no_account_msg: "Please add a receiving account",
    success_msg: "Operation successful",
    no_auth_title: "Identity Verification",
    no_auth_con:
      "You haven't completed identity verification. Would you like to verify now?",
    no_google_msg: "Google Authenticator",
    no_google_con:
      "You haven't linked Google Authenticator. Would you like to link it now?",
  },
  recharging: {
    recharge: "Deposit Funds",
    countdown: "Time Remaining",
    QRcodeExpired: "QR Code Expired",
    walletAddress: "Receiver's Address",
    copy: "Copy",
    tip1: "Complete your deposit before the deadline",
    tip2: "The order will expire if not completed",
    success: "Success",
    fail: "Failed",
    finish: "Done",
    info_title: "Deposit Details",
    info_recharge_success: "Deposit Successful",
    info_recharge_success_con1: "Your deposit of ",
    info_recharge_success_con2: " has been credited",
    info_recharge_failure: "Deposit Failed",
    info_recharge_failure_con: "Please try again or contact customer support",
    info_recharge_pending: "Deposit Processing",
    info_recharge_pending_con: "Please wait for the deposit result",
    info_recharge_balance: "Deposit Amount",
    info_recharge_crpyto: "Cryptocurrency Type",
    info_recharge_network: "Network Address",
    info_recharge_address: "Deposit Address",
    info_recharge_order: "Order ID",
    info_recharge_date: "Deposit Date",
    copied: "Copied Successfully",
  },
  withdrawInfo: {
    title: "Withdrawal Details",
    successful: "Success",
    failed: "Failed",
    failurePrompt: "Please try again or contact support",
    processing: "Processing",
    processingTip: "Please wait while we process your withdrawal",
    info_recharge_success_con1: "Your withdrawal of ",
    info_recharge_success_con2: " has been credited",
    withdrawalAmount: "Withdrawal Amount",
    receivingAccount: "Destination Account",
    withdrawalCurrency: "Cryptocurrency Type",
    withdrawalNetwork: "Network",
    orderNumber: "Order ID",
    withdrawalTime: "Withdraw Date",
  },
  transfer: {
    transferRecord: "History",
    page_title: "Transfer",
    out: "Transfer Out",
    out_sim: "Out",
    out_amount: "Please enter amount",
    in: "Transfer In",
    in_sim: "In",
    in_amount: "Please enter amount",
    btn: "Transfer",
    confirm: "Confirm",
    confirm_con: "Transfer Account",
    no_amount: "Amount is required",
    no_enough_balance: "Insufficient funds",
    account_same: "You cannot transfer to the same account",
    success: "Transfer successful",
    transfer_map_money: "Spot",
    transfer_map_stock: "Stock",
    transfer_map_futures: "Futures",
    transfer_map_forex: "Forex",
    transfer_map_trade: "Block Trade",
  },
  recordList: {
    financialRecords: "Funding Records",
    rechargeRecord: "Deposit",
    withdrawalRecord: "Withdraw",
    transfer: "Transfer",
  },
  accountMap: {
    cashAccount: "Spot ",
    stockAccount: "Stock ",
    contractAccount: "Futures ",
    foreignExchangeAccount: "Forex ",
  },
  topUpStatusMap: {
    review: "Under Review",
    success: "Success",
    failure: "Failed",
    unknown: "Pending",
  },
  withdrawStatusMap: {
    review: "Under Review",
    success: "Success",
    failure: "Failed",
    unknown: "Pending",
  },
  home: {
    login: "Log In",
    loginDesc: "Log in to view your assets",
    totalAssets: "Balance",
    fastTrading: "Fast Trade",
    recharge: "Deposit",
    today: "Today",
    index: "Index",
    hotSale: "Hot Sale",
    marketRecommend: "Markets",
    selfSelectedRecommend: "Custom Picks",
    notification: "Notice Announcement Content ...",
    optional: "Pick",
    homepage: "Home",
    market: "Markets",
    trade: "Trade",
    assets: "Assets",
    user: "User",
  },
  market: {
    stock: {
      updateTime: "Last Updated",
      riseAndFall: "Price Changes",
      up: "Up",
      down: "Down",
      limitUpPursuit: "Limit-Up Watch",
      profitMakingEffect: "Profit Potential",
      strong: "Strong",
      weak: "Weak",
      contrast: "Price Comparison",
      performance: "Top Performers",
      hot: "Hot Stocks",
      upList: "Top Gainers",
      downList: "Top Losers",
    },
  },
  trade: {
    header_stock: "Stocks",
    header_contract: "Futures",
    header_aibot: "Bots",
    header_ipo: "IPOs",
    header_forex: "Forex",
    header_block: "Blocks",
    header_block_long: "Block Trades",
    stock_open: "Open",
    stock_position: "Position",
    stock_search: "Search",
    stock_open_long: "Buy Long",
    stock_open_short: "Buy Short",
    stock_open_long_tab: "Long",
    stock_open_short_tab: "Short",
    stock_market_price: "Market",
    stock_limit_price: "Limit",
    stock_take_stop: "TP/SL",

    left_search: "Search",
    left_mine: "Favorites",
    left_stock: "Stock",
    left_contract: "Futures",
    left_bot: "Trading Bot",
    left_forex: "Forex",
    left_all: "All",

    stock_opening_take: "Take Profit",
    stock_opening_stop: "Stop Loss",
    stock_opening_price: "Price",
    stock_opening_price_market: "Market",
    stock_opening_price_limit: "Limit",
    stock_opening_price_latest: "Latest",
    stock_opening_price_title: "Price",
    stock_opening_price_tip: "Filled when price met",
    stock_opening_price_label: "Price",
    stock_opening_stock: "Stock",
    stock_opening_amount_mode: "Margin Mode",
    stock_opening_amount_limit_mode: "Limit",
    stock_opening_show_jump_type: "Transfer/Exchange/Deposit",
    stock_opening_amount_title: "Qty(shares)",
    stock_opening_no_balance: "Insufficient balance",
    stock_opening_enough_balance: "Balance",
    stock_opening_token_login: "Login",
    stock_opening_token_register: "Register",
    stock_opening_confirm_title: "Open Position Confirmation",
    stock_opening_amount: "Qty",
    stock_opening_no: "None",
    stock_opening_pay: "Pay",
    stock_opening_upfront: "Margin",
    stock_opening_fee: "Fees",
    stock_opening_trade_pw: "Trade Password",
    stock_opening_trade_pw_placeholder: "Enter trade password",
    stock_opening_confirm: "Confirm",
    stock_opening_search: "Search",
    stock_opening_jump_mode1: "Transfer",
    stock_opening_jump_mode2: "Exchange",
    stock_opening_jump_mode3: "Deposit",
    stock_opening_position_mode_cross: "Cross",
    stock_opening_position_mode_isolated: "Isolated",
    stock_account_balance: "Balance",
    stock_account_notification: "Deposit/Transfer in time",
    stock_opening_btn_transfer: "Transfer",
    stock_opening_btn_recharge: "Deposit",
    stock_opening_btn_trade: "Trade",

    stock_opening_stop_price: "Price",
    stock_opening_stop_amount: "Amount",
    stock_opening_stop_ratio: "Percentage",
    stock_opening_err_stock: "Select stock",
    stock_opening_err_min_balance: "Min trade size",
    stock_opening_err_price: "Enter price",
    stock_opening_err_take_price: "Enter take profit price",
    stock_opening_err_stop_price: "Enter stop loss price",
    stock_opening_err_limit: "Enter limit price",

    stock_opening_success: "Open success",
    stock_position_stock: "Stock/Status",
    stock_position_open: "Open/Available",
    stock_position_cost: "Price/Cost",
    stock_position_profit: "Profit/Ratio",
    stock_position_close: "Close",
    stock_position_close_order: "Close Order",
    stock_position_amount: "Quantity",
    stock_position_ongoing_amount: "Position Quantity",
    stock_position_all: "All",
    stock_position_btn: "Confirm",
    stock_position_update: "Update Order",
    stock_position_add_deposit: "Add Margin",
    stock_position_no_close_amount: "Enter Close Position Quantity",
    stock_position_success: "Operation Successful",
    stock_position_no_deposit: "Enter Margin",
    stock_position_cancel_title: "Cancel Order",
    stock_position_cancel_btn: "Cancel",
    stock_position_confirm_btn: "Confirm",
    stock_position_cancel_con: "Are you sure you want to cancel the order？",
    stock_position_status_none: "Open",
    stock_position_status_lock: "Lock",
    stock_position_status_open: "Position",
    stock_position_status_done: "Closed",
    stock_position_status_fail: "Failed",
    stock_position_status_cancel: "Canceled",
    stock_position_offset_long: "Buy",
    stock_position_offset_short: "Sell",
    stock_position_stop_price: "Price",
    stock_position_stop_amount: "Amount",
    stock_position_stop_ratio: "Percentage",
    stock_position_unlogin_title: " Not logged in yet?",
    stock_position_unlogin_con: "Login now",

    order_info_title_stock: "Stock Order",
    order_info_title_contract: "s Order",
    order_info_available_stock: "Available Stocks for Sale",
    order_info_available_contract: "Available Futures",
    order_info_profit: "Profit",
    order_info_ratio: "Ratio",
    order_info_update: "Update",
    order_info_cancel: "Cancel ",
    order_info_open_qty_contract: "Open Futures Quantity",
    order_info_open_qty_other: "Open Position Quantity",
    order_info_stop_profit_price: "Take Profit Price",
    order_info_stop_profit_amount: "Take Profit Amount",
    order_info_stop_profit_ratio: "Take Profit Percentage",
    order_info_stop_loss_price: "Stop Loss Price",
    order_info_stop_loss_amount: "Stop Loss Amount",
    order_info_stop_loss_ratio: "Stop Loss Percentage",
    order_info_value: "Order Value",
    order_info_copy: "Copied",

    contract_position_no_close_amount: "Enter Close Position Quantity",
    contract_position_ongoing_amount: "Position Quantity",
    contract_position_cost: "Price/Cost",
    contract_opening_err_contract: "Select Futures",
    contract_opening_err_amount: "Enter the amount",
    contract_opening_amount: "Qty",
    contract_opening_order_value: "Order Value",
    contract_opening_amount_title: "Quantity",
    contract_opening_contract: "Futures",
    contract_create_guest_btn: "Click for Guest Registration",
    contract_lots_amount: "Qty(lots)",
    contract_one_lot: "lot",

    ai_opening_order: "Orders",
    ai_opening_trade: "Trade",
    ai_opening_long: "Bullish",
    ai_opening_short: "Bearish",
    ai_opening_product_type: "Trade Product",
    ai_opening_time_zone: "Time Interval",
    ai_opening_network_amount: "Qty Grid",
    ai_opening_bigest_network: "Top Grid ",
    ai_opening_every_profit: "Profit per Interval",
    ai_opening_invest_amount: "Investment",
    ai_opening_balance: "Balance",
    ai_opening_login: "Login",
    ai_opening_register: "Register",
    ai_opening_confirm_order: "Confirm",
    ai_opening_predict_profit: "Est. PNL",
    ai_opening_confirm_btn: "Confirm",
    ai_opening_ai_quantifi_list: "AI Strategies",
    ai_opening_cash_wallet: "Spot Wallet",
    ai_opening_no_net: "Enter Grid Amount",
    ai_opening_no_product: "Select Product",
    ai_opening_no_invest_amount: "Enter Investment",
    ai_opening_min_invest_amount: "Min. Investment",
    ai_opening_trade_password: "Enter Password",
    ai_opening_success: "Trade Opened",
    ai_opening_pop_title: "Balance",
    ai_opening_pop_recharge: "Deposit Funds",
    ai_opening_pop_transfer: "Transfer Funds",
    ai_opening_perform_time: "Running Time",
    ai_opening_historical_profit_rate: "Historical Profit",
    ai_opening_24_profit_rate: "24h Profit",
    ai_opening_profit_margin: "Profit Margin",

    ai_position_title: "Trade Detail",
    ai_position_profit: "Profit",
    ai_position_timer: "Countdown",
    ai_position_end_trade: "Completed",
    ai_position_order_id: "Order No",

    ipo_title: "Orders",
    ipo_title_all: "All",
    ipo_title_pre: "Presale",
    ipo_title_going: "Opened",
    ipo_title_finish: "Closed",
    ipo_title_market: "Launched",
    ipo_detail_price: "Offering Price",
    ipo_detail_time: "Launch Time",
    ipo_detail_date: "Sale Date",
    ipo_detail_lever: "Leverage",
    ipo_detail_listing_price: "Listing Price",
    ipo_detail: "IPO Detail",
    ipo_opening_btn: "Buy",
    ipo_detail_item1: "Stock Symbol",
    ipo_detail_item2: "Offering Price",
    ipo_detail_item3: "Sale Start Date",
    ipo_detail_item4: "Sale End Date",
    ipo_detail_item5: "Launch Date",
    ipo_detail_item6: "Launch Price",
    ipo_detail_item7: "Min Buy Qty",
    ipo_detail_item8: "VIP Access",
    ipo_detail_item9: "Commission",
    ipo_detail_item10: "Buy Qty",
    ipo_detail_item11: "Market affiliation",
    ipo_detail_item12: "Order amount",
    ipo_detail_item13: "Order quantity",
    ipo_detail_item14: "Lock amount",
    ipo_detail_btn: "Purchase Now",
    ipo_account_balance: "IPO Balance",

    ipo_lottery_title1: "All",
    ipo_lottery_title2: "Pending",
    ipo_lottery_title3: "Won",
    ipo_lottery_title4: "Lost",
    ipo_lottery_title5: "Lock",
    ipo_lottery_title6: "Win",
    ipo_lottery_amount: "Number of Wins",
    ipo_lottery_detail: "Lottery Details",
    ipo_leveraged_trading: "leveraged",
    ipo_sub_ordinary: "Regulation",
    ipo_sub_leveraged: "Margin",
    ipo_sub_buy_code: "Buy Code",
    ipo_sub_buy_no_amount: "Enter Amount to Buy",
    ipo_sub_buy_no_code: "Enter Buy Code",

    forex_opening_title: "Forex",
    forex_position_title: "Forex/Status",
    trade_order_history: "History",
    left_search_result: "Result"

  },
  inviteFriends: {
    invite: "Invite",
    reward: "Rewards",
    banner_title: "Recommended friends can obtain",
    banner_desc: "Invite friends to earn money together",
    qrcode_title: "Invite QR code",
    save_img: "Save image",
    img_name: "My QR code",
    invite_code: "Referral Code",
    copy: "Copy",
    copy_success: "Copy success",
    url_title: "Invite link",
    copy_url: "Copy link",
    performance_title: "Recommended performance",
    details: "Recommending History",
    user: "User",
    performance: "Performance",
  },
  market: {
    market_header_optional: "Favorites",
    market_header_buy: "Buy",
    market_header_stock: "Stocks",
    market_header_contract: "Futures",
    market_header_ai: "Bots",
    market_header_forex: "Forex",

    market_optional_add: "Add Favorites",
    market_optional_no_optional: "You have not added anything to watchlist",
    market_optional_add_all: "Add All to Watchlist with One Click",
    market_optional_recommend_stock: "Hot Stocks",
    market_optional_recommend_crypto: "Hot Cryptos",
    market_optional_add_success: "Added Successful",
    market_optioanl_del_success: "Deleted Successful",

    market_optional_crypto_price: "Latest Price",
    market_optional_short: "Price Change",
    market_optioanl_ratio: "Long/Short",
    market_optional_stock: "STOCK",
    market_optional_contract: "CRYPTO",
    market_optional_forex: "FOREX",
    market_optional_blocktrade: "BLOCKTRADE",

    market_marketinfo_data: "Data",
    market_marketinfo_trade: "Trade",
    market_marketinfo_long: "Buy",
    market_marketinfo_short: "Sell",
    market_marketinfo_open: "Open",
    market_marketinfo_high: "High",
    market_marketinfo_amount: "Quantity",
    market_marketinfo_close: "Close",
    market_marketinfo_low: "Low",
    market_marketinfo_value: "Value",

    market_buy_title1: "Quick Buy",
    market_buy_title2: "Favorites",
    market_buy_title3: "My Orders",
    market_buy_fast_buy: "Buy",
    market_buy_fast_sell: "Sell",
    market_buy_fast_buy_btn: "Buy Crypto",
    market_buy_fast_sell_btn: "Sell Crypto",
    market_buy_fast_receive: "Receive",
    market_buy_fast_receive_sim: "Recv",
    market_buy_fast_pay: "Pay",
    market_buy_fast_estprice: "Estimated Price",
    market_buy_fast_search_title: "Currency Selection",
    market_buy_fast_search_input: "Enter Currency",
    market_buy_fast_no_amount: "Please enter an amount",
    market_buy_fast_noti_title: "Notification",
    market_buy_fast_noti_con:
      "Insufficient wallet balance. Please deposit or transfer funds",
    market_buy_fast_noti_cancel: "Deposit",
    market_buy_fast_noti_confirm: "Transfer",
    market_buy_fast_success: "Order Successful",
    market_buy_fast_account_title: "Account Selection",
    market_buy_fast_account_crypto: "Crypto",
    market_buy_fast_account_bank: "Bank Cards",
    market_buy_fast_account_add: "Add Payment Account",
    market_buy_optional_deal: "Volume",
    market_buy_optional_rate: "Rate",
    market_buy_optional_duaration: "Min",
    market_buy_optional_order_limit: "Order Limit",
    market_buy_optional_buy: "Buy",
    market_buy_optional_sell: "Sell",
    market_buy_optional_estreceive: "Est Receipt",
    market_buy_optional_limit_val: "Limit Value",
    market_buy_optional_confirm: "Confirm",

    market_buy_list_buy: "Buy",
    market_buy_list_sell: "Sell",
    market_buy_list_price: "Price",
    market_buy_list_amount: "Quantity",
    market_buy_list_wait_pay: "Waiting Pay",
    market_buy_list_wait_confirm: "Waiting Confirm",
    market_buy_list_wait_pay1: "Waiting Pay",
    market_buy_list_wait_confirm1: "Waiting Confirm",
    market_buy_list_complete: "Done",
    market_buy_list_cancel: "Canceled",
    market_buy_list_contact: "Trade Provider",
    market_buy_list_wait_buyer_confirm: "Waiting for Payment",
    market_buy_list_wait_buyer_con: "Transfer to the seller's bank account",
    market_buy_list_wait_con: "Payment made, waiting for seller's confirmation",
    market_buy_list_wait_result: "Seller paid, confirm receipt",
    market_buy_list_wait_buyer_bank: "Wait for seller's bank info",
    market_buy_list_wait_bank_no: "Bank No",
    market_buy_list_wait_account: "Account",
    market_buy_list_wait_total: "Total Price",
    market_buy_list_wait_price: "Price",
    market_buy_list_wait_amount: "Amount",
    market_buy_list_cancel_order: "Cancel Order",
    market_buy_list_paid: "Paid",
    market_buy_list_received: "Received",
    market_buy_list_trade_sccess: "Done",
    market_buy_list_paid_success: "Payment Successful",
    market_buy_list_pass_success: "Release Successful",
    market_buy_list_cancel_success: "Cancellation Successful",
    market_buy_list_pre_pay: "Est Payment",
    market_buy_list_firt_select: "Choose to add payment first",

    market_buy_chat_con1: "Order placed successfully",
    market_buy_chat_con2: "Wait for seller's payment",

    market_stock_country_us: "US",
    market_stock_country_japan: "JP",
    market_stock_country_india: "IN",
    market_stock_country_korea: "KR",
    market_stock_country_germany: "DE",
    market_stock_country_uk: "UK",
    market_stock_country_singapore: "SG",
    market_stock_country_hongkong: "HK",
    market_stock_country_malaysia: "MY",
    market_stock_country_us_long: "US",
    market_stock_country_japan_long: "Japan",
    market_stock_country_india_long: "India",
    market_stock_country_korea_long: "Korea",
    market_stock_country_germany_long: "Germany",
    market_stock_country_uk_long: "UK",
    market_stock_country_singapore_long: "Singapore",
    market_stock_country_hongkong_long: "Hong Kong",
    market_stock_country_malaysia_long: "Malaysia",
    market_stock_updatetime: "Updated Time",
    market_stock_description_title: "Movement",
    market_stock_description_des1: "Up",
    market_stock_description_des2: "Down",
    market_stock_description_long_end: "Lm.Up",
    market_stock_description_center: "Neu",
    market_stock_description_short_end: "Lm.Dn",
    market_stock_chase_movement: "Limit Up Chase",
    market_stock_chase_earning_effect: "Profit",
    market_stock_chase_strong: "Strong",
    market_stock_chase_movement_percentage: "Up/Down Comparison",
    market_stock_chase_todays_effect: "Today's Limit",
    market_stock_chase_long_sort: "Top Gainers",
    market_stock_chase_short_sort: "Top Losers",
    market_stock_hot: "Hot Stocks",
    market_ai_title1: "Default",
    market_ai_title2: "Historical ROI",
    market_ai_title3: "24h ROI",
    market_ai_title4: "Leverage",
    market_search_title: "Search",
    market_search_history: "History",
    market_search_recommend: "Trending",
    market_search_des: "20K+ Searches",

    market_buy_confirm_coin: "Order Confirmation",
    market_buy_will_pay: "You will pay",
    market_buy_will_sell: "You will sell",
    market_buy_will_receive: "You will receive",

    market_faster_available: "Available Balance",
    market_already_done: "Done",
    market_already_cancel: "Canceled",

    market_order_details_wait: "Wait",
    market_order_details_for_buyer: "Buyer pays",
    market_order_details_for_seller: "Seller confirms",
    market_order_details_con1: "Please base on the total price",
    market_order_details_con2:
      "Transfer to the bank card provided by the merchant",
  },
};
